<br>

# Basic Important Functions and Attributes

- ## np.array()
- ## dtype
- ## ndim
- ## shape
- ## size
- ## itemsize
- ## np.arange()
    - ## np.arrange(1,10)
    - ## np.arrange(1,10,2)
- ## np.reshape()
    - ## np.reshape(row,-1)
    - ## np.reshape(-1,row)
- ## astype()
- ## ones()
- ## zeros()
- ## random.random()
- ## linespace()
- ## np.identity()

- ## np.transpose() or .T
- ## np.reval()
- ## np.stack()
- ## np.hstack()
- ## np.vstack()
- ## np.split()
- ## np.vsplit()
- ## np.hsplit()

<br>

### install numpy

In [1]:
!pip install numpy
# already installed

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np

## np.array()

In [20]:
a = np.array([1,2,3]) # 1-D array
print(a)

[1 2 3]


## use ndim method for check Dimension

In [21]:
a.ndim

1

In [24]:
b = np.array([ [1,2,3] ]) # 2-D array
b

array([[1, 2, 3]])

In [23]:
b.ndim

2

In [26]:
c = np.array([ [ [1,2,3] ] ]) # 3-D array
c

array([[[1, 2, 3]]])

In [27]:
c.ndim

3

# dtype change data type

In [29]:
np.array([1,2,3],dtype=float) # float

array([1., 2., 3.])

In [31]:
np.array([1,2,3],dtype=str) # string

array(['1', '2', '3'], dtype='<U1')

In [11]:
np.array([0,1,2],dtype=bool) # bool

array([False,  True,  True])

# arange()
## arange is same as range() function

In [35]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# also we provide step argument
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

## shape 
## return the tuple (no of Inner Box ,no of elements)

In [4]:
ar = np.array([
    [1,3,4],
    [4,5,6]
])
ar

array([[1, 3, 4],
       [4, 5, 6]])

In [5]:
ar.ndim

2

In [70]:
ar.shape

(2, 3)

## 2 by 3 means (2 row , 3 column)

In [7]:
print("Inner Box   -> ",ar.shape[0])
print("Now of values each box -> ",ar.shape[1])

Inner Box   ->  2
Now of values each box ->  3


## try with 3D 

In [72]:
ar = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
])
print(ar)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [73]:
ar.shape

(1, 3, 3)

# what is 1 ?

In [ ]:
"""
[  
    [ ---------------------> open bracket
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ] ---------------------> close bracket    only 1 bracker
]
"""

In [90]:
ar = np.array([
    [ #---------------------> open bracket   
        [1,2,3],
        [4,5,6],
    ]# ---------------------> close bracket
    ,
    [ #---------------------> open bracket   
        [1,2,3],
        [4,5,6],
    ],# ---------------------> close bracket
   
]) # TOTAL 2 BRACKETS
print(ar)
# it means  2 ,2(row), 3(col) --> shape

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [78]:
ar.shape

(2, 2, 3)

In [83]:
ar.shape

(2, 2, 3)

# np.reshape()
## change shape of array

In [21]:
ar = np.array([[1,2,3]])
print(ar)
print()
print(ar.shape)

[[1 2 3]]

(1, 3)


In [25]:
ar.reshape(3,1) # change rows with column

array([[1],
       [2],
       [3]])

## Note reshpe are depend on array means e.g if actuall array shape is 2 rows and 2 column than it is not possible to reshape with 4 by 4 etc.


In [44]:
ar = np.array([[1,2,3],[4,5,6]])
print(ar.shape)
print()
print(ar)

(2, 3)

[[1 2 3]
 [4 5 6]]


In [47]:
ar.reshape(4,4)

ValueError: cannot reshape array of size 6 into shape (4,4)

## because actual shape is 2 x 3 = 6 and reshape only possible if the value is multiply is 6 

## posible Sequence

In [54]:
# 3 * 2
# 2 * 3
# 1 * 6
# 6 * 1

print(ar.reshape(3,2))
print()
print(ar.reshape(2,3))
print()
print(ar.reshape(1,6))
print()
print(ar.reshape(6,1))
print()



[[1 2]
 [3 4]
 [5 6]]

[[1 2 3]
 [4 5 6]]

[[1 2 3 4 5 6]]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]



## we also use -1
### -1 are auto adjust the rows or col

In [55]:
x = -1
ar.reshape(3,x) # 3 , x(2) = 6

array([[1, 2],
       [3, 4],
       [5, 6]])

In [56]:
ar.reshape(x,3) # x(2) , 3 = 6

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
ar.reshape(1,x) # 1 , x(6) = 6

array([[1, 2, 3, 4, 5, 6]])

In [59]:
ar.reshape(6,x) # 6 , x(1) = 6

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## we can't use -1 in both (row,col)

In [60]:
ar.reshape(-1,-1)

ValueError: can only specify one unknown dimension

# size
## return all no of Element in arru

In [91]:
ar

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [92]:
# 12 item in array
print(ar.size)

12


# itemsize
## return size(in bytes) of array that are store in memory

In [93]:
print(ar.itemsize)

8


# astype()
## change datatype 


In [97]:
ar = np.array([[1,2,3],[4,5,6]])
print(ar)

[[1 2 3]
 [4 5 6]]


In [100]:
# now change type
ar.astype(str)

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U21')

### but actual data are not changed

In [101]:
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
# change in float
ar.astype(float)

array([[1., 2., 3.],
       [4., 5., 6.]])

# ones()
## create 1 Elemets array

In [119]:
np.ones((3,3)) # (row,col) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [118]:
np.ones((2,3,3)) # (row,col) # ed array

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

# zeros()
## create 0 Elemets array

In [120]:
np.zeros((3,3)) # (row,col)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# random.random()
## return random no of array

In [124]:
np.random.random((2,3)) # 2 by 3

array([[0.38588594, 0.18167721, 0.21157822],
       [0.62204147, 0.7327931 , 0.20507913]])

In [126]:
np.random.random((3,2,2)) 

array([[[0.97639172, 0.49759868],
        [0.47695797, 0.62066082]],

       [[0.97487262, 0.51999988],
        [0.7824305 , 0.22655737]],

       [[0.26543512, 0.97902777],
        [0.13623622, 0.02901384]]])

# linspace()
## return the array in which all points are equal Distances

In [136]:
np.linspace(1,6,6) #(start,max,stop)

array([1., 2., 3., 4., 5., 6.])

In [146]:
np.linspace(1,6,7) #(start,max,stop)

array([1.        , 1.83333333, 2.66666667, 3.5       , 4.33333333,
       5.16666667, 6.        ])

# identity()
## return the dignal of 1 array

In [158]:
np.identity(3) # 3 x 3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [161]:
np.identity(2) # 2 x 2

array([[1., 0.],
       [0., 1.]])

# np.transpose() or .T
# convert row to col and col to row

In [176]:
ar = np.arange(1,10).reshape(1,3,3)
print(ar)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [177]:
np.transpose(ar)

array([[[1],
        [4],
        [7]],

       [[2],
        [5],
        [8]],

       [[3],
        [6],
        [9]]])

In [179]:
# also use T
ar.T

array([[[1],
        [4],
        [7]],

       [[2],
        [5],
        [8]],

       [[3],
        [6],
        [9]]])

# np.reval()
## Convert any array to 1-D

In [181]:
np.ravel(ar)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Merge (Stacking)

In [190]:
ar1 = np.arange(1,7).reshape(2,3)
ar2 = np.arange(7,10).reshape(1,3)

In [191]:
print(ar1)

[[1 2 3]
 [4 5 6]]


In [192]:
print(ar2)

[[7 8 9]]


In [193]:
print(ar1.shape)
print(ar2.shape)

(2, 3)
(1, 3)


# verticle Stack Posible

In [200]:
np.vstack((ar1,ar2))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# but Horizontal Stack not posible because 2nd array have only 1 column and other array have 2 Column

<br>

## add 1 more column in ar2

# Horizontal Stack

In [205]:
new = np.vstack((ar2,ar2))
new

array([[7, 8, 9],
       [7, 8, 9]])

## Now check arr1 and new have same column

In [207]:
print(ar1.shape)
print(new.shape)

(2, 3)
(2, 3)


# Now apply verticle Stack

In [245]:
merge =  np.vstack((ar1,new))
merge

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9]])

In [211]:
print(merge.shape)

(4, 3)


# np.stack()
## np.stack also merge the array but in stack we also define axis

# Note In np.stack we can only merge with the same shape

In [256]:
x = np.array([[
    [1,2,3],
    [4,5,6]
]])

y = np.array([[
    [7,8,9],
    [10,11,12]
]])

In [257]:
print(x)

[[[1 2 3]
  [4 5 6]]]


In [258]:
print(y)

[[[ 7  8  9]
  [10 11 12]]]


## simple np.stack

In [266]:
np.stack((x,y),axis=0)

array([[[[ 1,  2,  3],
         [ 4,  5,  6]]],


       [[[ 7,  8,  9],
         [10, 11, 12]]]])

## verticle stack

In [263]:
np.vstack((x,y))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# now change axis in stack

In [270]:
print(np.stack((x,y),axis=1)) # axis 1 change to order

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


# Spliting 

# verticle split

In [281]:
np.vsplit(merge,2)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9],
        [7, 8, 9]])]

In [293]:
sp1,sp2 = np.vsplit(merge,2)

In [294]:
print(sp1)

[[1 2 3]
 [4 5 6]]


In [295]:
print(sp2)

[[7 8 9]
 [7 8 9]]


# Horizontal Split

In [296]:
x = np.array([
    [1,2,3,4],
    [5,6,7,8],
])

In [297]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [335]:
np.hsplit(x,2)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [308]:
sp1,sp2 = np.hsplit(x,2)

In [309]:
print(sp1)

[[1 2]
 [5 6]]


In [310]:
print(sp2)

[[3 4]
 [7 8]]


# np.split()
## also split on horizontal and vertical
## axis 0 = verticle
## axis 1 = horizontal


In [336]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [345]:
np.split(x,2,axis=0) # verticle

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [346]:
# vsplit
np.vsplit(x,2) # verticle

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [348]:
np.split(x,2,axis=1) # horizontal

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [347]:
np.hsplit(x,2) # horizontal

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]