In [1]:
import numpy as np

In [4]:
ar1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
ar2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Scaler Operation
## we are working on a array with Single value

In [7]:
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
ar1 + 1 # add

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [11]:
ar1 - 1 # sub

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
ar1 * 2 # multiply

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [13]:
ar1 * 0

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [16]:
ar1 / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

## We are used all operators

<br>

# relational operations

In [19]:
print(ar1)
ar1 > 2

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [20]:
print(ar1)
ar1 == 2

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[False,  True, False],
       [False, False, False],
       [False, False, False]])

In [21]:
print(ar1)
ar1 <= 2

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

# we are used all relational operators
<br>

# Vector Operations
## Operations on two or more arrays

In [26]:
print(ar1,"\n\n",ar2)
ar1 + ar2

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [27]:
print(ar1,"\n\n",ar2)
ar1 - ar2

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [28]:
print(ar1,"\n\n",ar2)
ar1 ** ar2

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[        1,         4,        27],
       [      256,      3125,     46656],
       [   823543,  16777216, 387420489]])

## We are used all operatons

<br><br>
## Some more Useful Function

# np.max()
## return maximum number

In [52]:
print(ar1)
np.max(ar1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


9

In [53]:
# we also use axis means column wise and row wise
np.max(ar1,axis=0)

array([7, 8, 9])

In [54]:
np.max(ar1,axis=1)

array([3, 6, 9])

# np.min()
## return minimum number

In [31]:
print(ar1)
ar1

[[1 2 3]
 [4 5 6]
 [7 8 9]]


1

In [55]:
print(np.min(ar1,axis=0))
print(np.min(ar1,axis=1))

[1 2 3]
[1 4 7]


# np.sum()
## return sum of all array 

In [56]:
print(ar1)
np.sum(ar1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


45

In [57]:
print(np.sum(ar1,axis=0))
print(np.sum(ar1,axis=1))

[12 15 18]
[ 6 15 24]


# np.prod()
## return product of all array 

In [58]:
print(ar1)
np.prod(ar1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


362880

In [59]:
print(np.prod(ar1,axis=0))
print(np.prod(ar1,axis=1))

[ 28  80 162]
[  6 120 504]


# np.mean()
## return mean of all array 

In [60]:
print(ar1)
np.mean(ar1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


5.0

In [50]:
print(ar1.mean(axis=0))
print(ar1.mean(axis=1))

[4. 5. 6.]
[2. 5. 8.]


# np.median()
## return median of all array 

In [61]:
print(ar1)
np.median(ar1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


5.0

In [63]:
print(np.median(ar1,axis=0))
print(np.median(ar1,axis=1))

[4. 5. 6.]
[2. 5. 8.]


# np.std()
## return standard Deviation

In [64]:
print(ar1)
np.std(ar1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2.581988897471611

In [66]:
print(np.std(ar1,axis=0))
print(np.std(ar1,axis=1))

[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]


# np.var()
## return Variance

In [69]:
print(ar1)
print()
print(np.var(ar1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6.666666666666667


In [70]:
print(np.var(ar1,axis=0))
print(np.var(ar1,axis=1))

[6. 6. 6.]
[0.66666667 0.66666667 0.66666667]


# Trigonometry Funtions

# np.sin()

In [71]:
np.sin(ar1)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

# np.cos

In [74]:
np.cos(ar1)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

# np.tan()

In [75]:
np.tan(ar1)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

# np.sinh()

In [76]:
np.sinh(ar1)

array([[1.17520119e+00, 3.62686041e+00, 1.00178749e+01],
       [2.72899172e+01, 7.42032106e+01, 2.01713157e+02],
       [5.48316123e+02, 1.49047883e+03, 4.05154190e+03]])

# np.cosh()

In [79]:
np.cosh(ar1)

array([[1.54308063e+00, 3.76219569e+00, 1.00676620e+01],
       [2.73082328e+01, 7.42099485e+01, 2.01715636e+02],
       [5.48317035e+02, 1.49047916e+03, 4.05154203e+03]])

# np.tanh()

In [83]:
np.tanh(ar1)

array([[0.76159416, 0.96402758, 0.99505475],
       [0.9993293 , 0.9999092 , 0.99998771],
       [0.99999834, 0.99999977, 0.99999997]])

# np.dot()
## return dot product

In [94]:
np.dot(ar1,ar2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# np.exp()
## return Exponent 

In [98]:
np.exp(ar1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

# np.log()
## return log

In [103]:
np.log(ar1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

# np.round()
## round the nearest value of before point

In [128]:
new = np.array([
       [20.04013569, 20.52509211, 11.35635698],
       [62.79092511,  1.69624541, 24.45879096],
       [40.308244  ,  4.76066451, 90.0927468 ]])

new

array([[20.04013569, 20.52509211, 11.35635698],
       [62.79092511,  1.69624541, 24.45879096],
       [40.308244  ,  4.76066451, 90.0927468 ]])

In [129]:
np.round(new)

array([[20., 21., 11.],
       [63.,  2., 24.],
       [40.,  5., 90.]])

# np.floor()
## round the previous value of before point
## 6.9 -> 6

In [127]:
print(new)
np.floor(new)

[[20.04013569 20.52509211 11.35635698]
 [62.79092511  1.69624541 24.45879096]
 [40.308244    4.76066451 90.0927468 ]]


array([[20., 20., 11.],
       [62.,  1., 24.],
       [40.,  4., 90.]])

# np.ceil()
## round the next value of before point
## 6.9 -> 7

In [131]:
np.ceil(new)

array([[21., 21., 12.],
       [63.,  2., 25.],
       [41.,  5., 91.]])