# Indexing and slicing

In [8]:
import numpy as np

In [9]:
a1 = np.arange(10)
a2 = np.arange(12).reshape((3,4))
a3 = np.arange(8).reshape((2,2,2))

In [10]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# indexing and Slicing are same as normal indexing like string list etc 

In [11]:
a1[0] # first element

0

In [12]:
a1[1] # 2nd element

1

In [13]:
a1[-1] # reverse indexing

9

## 2d array

In [15]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# frist select column

In [16]:
a2[0] # ----> [ 0,  1,  2,  3]

array([0, 1, 2, 3])

## now select element 

In [17]:
a2[0][0] # [ (0) , 1,  2,  3]

0

In [18]:
a2[0][1]

1

In [20]:
a2[0][-1] # last

3

# now change column

In [21]:
a2[1][-1] # last

7

In [18]:
a2[2][-1] # last

11

# also used a2[2,-1]

In [19]:
print(a2[2][-1])
print(a2[2,-1])

11
11


# 3d array

In [21]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

## 3D = two 2D Arrays

# Now Extract 5

In [22]:
# this is 1st 2D array
a3[0]

array([[0, 1],
       [2, 3]])

In [23]:
a3[1] # this is 2nd 2D array

array([[4, 5],
       [6, 7]])

In [24]:
# select 1st 2d array
a3[0]

array([[0, 1],
       [2, 3]])

# Now select rows

In [25]:
a3[1][0]

array([4, 5])

# Now select column

In [26]:
a3[1][0][1]

5

In [31]:
# also used
a3[1,0,1]

5

# Slicing

In [27]:
print(a1)

a1[0:3]

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2])

In [33]:
a1[0:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [34]:
a1[4:6]

array([4, 5])

# 2D array

In [28]:
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# select first row

In [29]:
a2[0]

array([0, 1, 2, 3])

# now slice it

In [30]:
a2[0][0:2]

array([0, 1])

In [31]:
# also use 
a2[0,0:2]

array([0, 1])

In [32]:
a2[0,2:4]

array([2, 3])

# 3D array

In [33]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# now select array
## means 3D array = two 2D array

In [34]:
a3[0] # select fist 2 D ARRAY

array([[0, 1],
       [2, 3]])

# now select rows

In [35]:
a3[0][0]

array([0, 1])

# now Slice it

In [46]:
a3[0][0][0:2]

array([0, 1])

In [47]:
# or
a3[0,0,0:2]

array([0, 1])

# Skip Argument

In [48]:
                #start 1 to 9
a3_D = np.arange(1,33).reshape((2,4,4))
a3_D

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]]])

# select 0 to end

In [50]:
a3_D[0:]

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]]])

# select 2D

In [51]:
a3_D[0:1]

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

# NOW use slice and skip argument

In [53]:
a3_D[0:][0]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [54]:
a3_D[0:][0][0:4]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [55]:
a3_D[0:][0][0:4:1] # 1 is the skip argument

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [79]:
a3_D[0:][0][0:4:2] # 2 is the skip argument

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

# Extract 1,3,9,11

In [80]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
a2[::2] # skip row

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [82]:
a2[::2,1:] # skip 0 8

array([[ 1,  2,  3],
       [ 9, 10, 11]])

In [83]:
a2[::2,1::2] # skip 2,10

array([[ 1,  3],
       [ 9, 11]])

# Example 2

In [84]:
a2 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Extract  

# 6 7 10 11 

## skip 1st row

In [87]:
a2[1::]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# skip 1st 2 column

In [89]:
a2[1::,::]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Now just start with 2

In [90]:
a2[1::,2::]

array([[ 6,  7],
       [10, 11]])

# ITERATION

# 1-D Array

In [91]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


# 2-D

In [93]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


# iterate all element

In [269]:
for i in a2:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11


# Select 1st Column

In [96]:
for i in a2:
    row = 0
    print(i[row])

0
4
8


# Select 2nd Column

In [97]:
for i in a2:
    row = 1
    print(i[row])

1
5
9


# Select 1st and last Column

In [109]:
for i in a2:
    print(i[0],i[-1])

0 3
4 7
8 11


# 3-D 

In [118]:
for i in a3:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


# iteration all Element

In [283]:
for i in a3:
    for j in i:
        for k in j:
            print(k)

0
1
2
3
4
5
6
7


# select 0,1  4,5

In [126]:
for i in a3:
    print(i[0])

[0 1]
[4 5]


# select 2,3  6,7

In [131]:
for i in a3:
    print(i[1])

[2 3]
[6 7]


In [7]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

|0 1| |2 3|<br>
|4 5| |6 7|<br><br> 
|4 5| |8 9|

## Working on 2d array

In [158]:
for pos,i in enumerate(a2):
    print(i,pos)

[0 1 2 3] 0
[4 5 6 7] 1
[ 8  9 10 11] 2


# So Sequence is row 1, row 2 row 3

# extract 
# 0 1  2 3
# 4 5  6 7 

In [182]:
for pos,i in enumerate(a2):
    if pos != 2:
        print(i[0::],pos)

[0 1 2 3] 0
[4 5 6 7] 1


In [189]:
for pos,i in enumerate(a2):
    if pos != 2:
        print(i[0::])

[0 1 2 3]
[4 5 6 7]


# np.nditer()
## this function iterate the elements we dont need to nested loop

In [284]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


## 3D array

In [287]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
