## What is numpy?
<br>

- ## NumPy is the fundamental package for scientific computing in Python.
<br>

- ## It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.
<br>

- ## At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

<br>

## Numpy Arrays Vs Python Sequences
<br><br>

- ## NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
<br>

- ## The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.
<br>

- ##  NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.
<br>

- ##  A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [7]:
import numpy as np

# 1 - D Array / scalar

## An Array has 1 row called 1-D Array
## 1-D array also know as Scalar

<img src="../../images/1d.jpg" style="display: block;margin-left: auto;margin-right: auto;
  width: 50%; border-radius:0px 10px 10px 10px; height:50%;">


In [64]:
arr = np.array( [1,2,3] )

In [65]:
arr

array([1, 2, 3])

## check shape or ndim

In [66]:
print("Dim --> ",arr.ndim) # check dimension

Dim -->  1


# Traverse

<img src="../../images/1d.jpg" style="display: block;margin-left: auto;margin-right: auto;
  width: 50%; border-radius:0px 10px 10px 10px; height:50%;">


In [67]:
arr

array([1, 2, 3])

In [68]:
pos = 0
arr[pos]

1

In [69]:
length = len(arr)
print(length)

3


In [70]:
position = 0

while position < length:
    print(arr[position],end=" ")
    position+=1

1 2 3 

# Array vs Matrix

# Array are stored Multiple data types

In [71]:
# here we can say that it is array
x = [
    [1,2,3,["hello","Mubeen"]]
]

In [5]:
x

[[1, 2, 3, ['hello', 'Mubeen']]]

# Matrix

# Matrix are stored Only Single Data Type
<br>

# Matrix have fix length
* ## Means e.g if i have 2-D array and the size of (rows ,column) are same and Single Data type are stored in it than we can say that it is Matrix

In [72]:
np.array([
    [1,2,3],
    [4,5,6]
])

array([[1, 2, 3],
       [4, 5, 6]])

# 2 - D

## Two (1-D) Array Called 2-D
<br>

## which means [(rows,Column)] 

<img src="../../images/2d.jpg" style="display: block;margin-left: auto;margin-right: auto;
  width: 80%; border-radius:0px 10px 10px 10px; height:80%;">


In [363]:
arr = np.array(
    [ # ----------------------> Consider as Box
    [1,2,3]
    ]
)

In [364]:
arr

array([[1, 2, 3]])

In [81]:
# check dimension
arr.ndim

2

In [79]:
# check shape dimension 
arr.shape

(1, 3)

## shape represent that
* ### (1,3) 1 represt the box
* ### (1,3) 3 represt that no of elements or values

# add more row

<img src="../../images/2_1d.jpg" style="display: block;margin-left: auto;margin-right: auto;
  width: 80%; border-radius:0px 10px 10px 10px; height:80%;">


In [82]:
arr = np.array(
    [ # ----------------------> Consider as Box
    [1,2,3], #---------> row 0 3 elements
    [4,5,6]  #---------> row 1 3 elements
    ]
)

In [83]:
arr.shape

(2, 3)

## Traverse

In [85]:
# select 0 row
arr[0]

array([1, 2, 3])

# access elements in 0 row

In [89]:
print(arr[0][0])
print(arr[0][1])
print(arr[0][2])

1
2
3


In [90]:
# select 1 row
arr[1]

array([4, 5, 6])

# access elements in 1 row

In [94]:
print(arr[1][0])
print(arr[1][1])
print(arr[1][2])

4
5
6


In [115]:
print(arr[0][0],arr[0][1],arr[0][2])
print(arr[1][0],arr[1][1],arr[1][2])

1 2 3
4 5 6


# Travers with loop

In [129]:
row = 0
col = 0

In [130]:
arr.shape

(2, 3)

In [131]:
while row < 2:
    print(row)
    row += 1

0
1


In [132]:
while col < 3:
    print(col)
    col += 1

0
1
2


## Now merge the loop

In [124]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [125]:
arr.shape

(2, 3)

In [140]:
row = 0
col = 0

In [141]:
while row < 2:
    col = 0 # for next row
    while col < 3:
        print(arr[row][col])
        col += 1
    row += 1

1
2
3
4
5
6


## use .shape method

In [143]:
row = 0
col = 0

In [144]:
arr.shape

(2, 3)

In [145]:
while row < arr.shape[0]:
    col = 0 # for next row
    while col < arr.shape[1]:
        print(arr[row][col])
        col += 1
    row += 1

1
2
3
4
5
6


# Easy way to use for loop

In [148]:
for row in arr:
    print(row)

[1 2 3]
[4 5 6]


In [164]:
for row in arr:
    for col in row:
        print(col)

1
2
3
4
5
6


In [165]:
for row in arr:
    for col in row:
        print(col,end=" ")

1 2 3 4 5 6 

In [167]:
for row in arr:
    for col in row:
        print(col,end=" ")
    print(" ")

1 2 3  
4 5 6  


In [169]:
print(arr[0])
print(arr[1])

[1 2 3]
[4 5 6]


In [170]:
arr.shape

(2, 3)

## add more row

<img src="../../images/2_2d.jpg" style="display: block;margin-left: auto;margin-right: auto;
  width: 80%; border-radius:0px 10px 10px 10px; height:80%;">


In [237]:
arr = np.array(
    [ # ----------------------> Consider as Box
    [1,2,3], #---------> row 0 3 elements
    [4,5,6], #---------> row 1 3 elements
    [7,8,9]  #---------> row 2 3 elements
    ]
)

In [174]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [172]:
arr.shape

(3, 3)

In [184]:
row = 0
while row < arr.shape[0]:
    print(arr[row])
    row += 1

[1 2 3]
[4 5 6]
[7 8 9]


In [188]:
row = 0
col = 0
while row < arr.shape[0]:
    col = 0 # for next row
    while col < arr.shape[1]:
        print(arr[row][col])
        col += 1
    
    row += 1

1
2
3
4
5
6
7
8
9


In [267]:
row = 0
col = 0
while row < arr.shape[0]:
    col = 0 # for next row
    while col < arr.shape[1]:
        print(arr[row][col],end=" ")
        col += 1
    print()
    row += 1

1 2 3 
4 5 6 
7 8 9 


# 3-D

## 1 (2-D Matrix) that are Store in One more Box called 3-D 

<img src="../../images/3d.jpg" style="display: block;margin-left: auto;margin-right: auto;
  width: 80%; border-radius:0px 10px 10px 10px; height:80%;">


In [308]:
arr = np.array(
    [#----------------------------------------------- 3-D box   
    
    [ #----------------------------------------------- 2-D box   
    [1,2,3], #---------> row 0 3 elements
    [4,5,6], #---------> row 1 3 elements
    [7,8,9]  #---------> row 2 3 elements
    ] #----------------------------------------------- 2-D box   

    ] #----------------------------------------------- 3-D box   

)

In [309]:
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [298]:
arr.ndim

3

In [310]:
arr.shape

(1, 3, 3)

- ## (1, 3, 3) ,1st 1 represent outer box of 3-D
- ## (1, 3, 3) ,2nd 3 represrnt the  rows means 3 row
- ## (1, 3, 3) ,3rd 3 represrnt that Each rows have 3 values


In [313]:
select_2D = 0
row = 0
col = 0

In [315]:
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [314]:
arr[select_2D][row][col]

1

## select_2d means no of 2D arrays that are exist in outer Box

In [316]:
arr[select_2D]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# select rows

In [317]:
arr[select_2D][0]

array([1, 2, 3])

In [318]:
arr[select_2D][1]

array([4, 5, 6])

In [319]:
arr[select_2D][2]

array([7, 8, 9])

In [321]:
# itereation
for i in arr:
    print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [323]:
# access elements
for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9


In [324]:
arr.shape

(1, 3, 3)

# add more 2D

<img src="../../images/3d_2.jpg" style="display: block;margin-left: auto;margin-right: auto;
  width: 80%; border-radius:0px 10px 10px 10px; height:80%;">


In [325]:
arr = np.array(
    [#----------------------------------------------- 3-D box   
    
    [ #----------------------------------------------- 2-D box 1   
    [1,2,3], #---------> row 0 3 elements
    [4,5,6], #---------> row 1 3 elements
    [7,8,9]  #---------> row 2 3 elements
    ] #----------------------------------------------- 2-D box 1
    ,
    
    [ #----------------------------------------------- 2-D box 2  
    [11,12,13], #---------> row 0 3 elements
    [14,15,16], #---------> row 1 3 elements
    [17,18,19]  #---------> row 2 3 elements
    ] #----------------------------------------------- 2-D box 2

        
        
        
    ] #----------------------------------------------- 3-D box   

)

In [326]:
arr.shape

(2, 3, 3)

In [327]:
arr.ndim

3

# two 2-D Metrix are exist

In [328]:
arr[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [330]:
arr[1]

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [331]:
arr.shape

(2, 3, 3)

In [333]:
# select 2nd metrix
arr[1]

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

# select rows

In [334]:
arr[1][1]

array([14, 15, 16])

# select values

In [335]:
arr[1][1][2]

16

## iteration 3-D

In [336]:
arr.shape

(2, 3, 3)

In [337]:
arr_2d = arr.shape[0]
rows = arr.shape[1]
col = arr.shape[2]

In [349]:
i = 0
j = 0
k = 0

In [340]:

# iterate 2-D
while i < arr_2d:
    print(i)
    i+=1

0
1


In [348]:
while i < arr_2d:
    print(arr[i])
    i+=1
    print()

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[11 12 13]
 [14 15 16]
 [17 18 19]]



In [362]:
i = 0
j = 0
k = 0

# no od 2D
while i < arr_2d:
    j = 0 # reset
    
    # select rows
    while j < rows:
       
        k = 0 # reset 0
        
        # select values
        while k < col:
            print(arr[i][j][k],end=" ")
            k+=1
        print()
        j+=1
    
    print()
    i+=1
    

1 2 3 
4 5 6 
7 8 9 

11 12 13 
14 15 16 
17 18 19 

