<img src="../../images/spin.jpg" style="display: block;margin-left: auto;margin-right: auto;
  width: 80%; border-radius:0px 10px 10px 10px; height:80%;">


## Spin With Normal Indexing

In [1]:
import numpy as np

In [2]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [3]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
arr.ndim

2

In [5]:
arr.shape

(3, 3)

In [6]:
def right_2d_spin(array):
   
    t1 = array[0,0]
    array[0,0] = array[2,0]
    
    t2 = array[0,2]
    array[0,2] = t1
    
    t1 = array[2,2]
    array[2,2] = t2
    array[2,0] = t1
    
    t2 = array[0,1]
    array[0,1] = array[1,0]
    
    t1 = array[1,2]
    array[1,2] = t2
    
    t2 = array[2,1]
    array[2,1] = t1
    array[1,0] = t2



In [7]:
# copy array
temp = arr.copy()

In [8]:
temp

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
right_2d_spin(temp)
temp

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

# again spin

In [10]:
right_2d_spin(temp)
temp

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

# spin

In [11]:
right_2d_spin(temp)
temp

array([[3, 6, 9],
       [2, 5, 8],
       [1, 4, 7]])

# again spin

In [12]:
right_2d_spin(temp)
temp

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Fancy Indexing

In [13]:
arr = np.arange(12).reshape(4,3)

In [14]:
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


## Now access 1st and third row

In [15]:
arr[::2]

array([[0, 1, 2],
       [6, 7, 8]])

# Now access 1st, thrid and forth

In [16]:
print(arr[::][0])
print(arr[::][2])
print(arr[::][3])

[0 1 2]
[6 7 8]
[ 9 10 11]


## So it is not possible to access in this pattern

# Try with Fancy Indexing
<br>

# array[ [rows],[columns] ]


In [17]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
arr[[0,2,3]] # access 1st , third and fourth row

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## access specfic columns

In [19]:
arr[::,[0]] # all rows and 0 columns

array([[0],
       [3],
       [6],
       [9]])

In [20]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## access
## [ 3,  4,  5],
## [ 6,  7,  8],
<br>

## and select mid column 4,7

In [21]:
arr[[1,2]] 

array([[3, 4, 5],
       [6, 7, 8]])

In [22]:
arr[[1,2],[1]] 

array([4, 7])

In [23]:
arr[::,[1]] 

array([[ 1],
       [ 4],
       [ 7],
       [10]])

# Now Spin Array with Fancy Indexing

In [24]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [25]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
def spin(arr):
    t = arr[[0],[0,2]]     
    arr[[0],[2]] = t[0]
    
    t[0] = arr[[2],[2]]
    arr[[2],[2]] = t[1]
    
    t[1] = arr[[2],[0]]
    arr[[2],[0]] = t[0]
    
    arr[[0],[0]] = t[1]
    
    t[0] = arr[[0],[1]]
    t[1] = arr[[1],[2]]
    
    arr[[1],[2]] = t[0]
    t[0] = arr[[2],[1]]
    
    arr[[2],[1]]= t[1]
    t[1] = arr[[1],[0]]
    
    arr[[0],[1]] = t[1]
    arr[[1],[0]] = t[0]
    return arr


In [27]:
for i in range(4):
    print(spin(arr),end="\n\n")


[[7 4 1]
 [8 5 2]
 [9 6 3]]

[[9 8 7]
 [6 5 4]
 [3 2 1]]

[[3 6 9]
 [2 5 8]
 [1 4 7]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]



# Boolean Indexing

# we also apply a condition with Boolean Indexing

In [28]:
arr = np.random.randint(1,100,24).reshape(6,4)
print(arr)

[[30 51  5 33]
 [ 2 96 32  7]
 [85 57 31 64]
 [76 71 31 98]
 [ 6 77 34 34]
 [92 93 15 83]]


## Now find all Numbers greater than 50

# using boolean indexing

In [29]:
# arr[conditions]
arr > 50

array([[False,  True, False, False],
       [False,  True, False, False],
       [ True,  True, False,  True],
       [ True,  True, False,  True],
       [False,  True, False, False],
       [ True,  True, False,  True]])

In [30]:
# now add in arr[] brackets
arr[arr > 50]

array([51, 96, 85, 57, 64, 76, 71, 98, 77, 92, 93, 83])

# Find even numbers

In [31]:
arr[arr %2 == 0]

array([30,  2, 96, 32, 64, 76, 98,  6, 34, 34, 92])

# find all even numbers only greater than 50

In [32]:
arr[ (arr %2 == 0) & (arr > 50) ]

array([96, 64, 76, 98, 92])

# find all numbers that not divisible by 7

In [33]:
arr[arr % 7 != 0]

array([30, 51,  5, 33,  2, 96, 32, 85, 57, 31, 64, 76, 71, 31,  6, 34, 34,
       92, 93, 15, 83])

In [34]:
arr[~(arr % 7 == 0)]
# ~ is the logical not 

array([30, 51,  5, 33,  2, 96, 32, 85, 57, 31, 64, 76, 71, 31,  6, 34, 34,
       92, 93, 15, 83])