- ## *np.delete()*
- ## *np._s[::]*
- ## *np.insert()*
- ## *np.append()*
- ## *np.trim_zeros()*

# *np.delete()*

<br>

- ### In NumPy, the delete() function is used to remove elements from an array. The syntax of this function is numpy.delete(arr, obj, axis=None), where arr is the input array, obj specifies the index or indices to remove, and axis argument is optional which specifies the dimension from which elements are to be removed.
<br>

- ### By using the delete() function, we can remove elements from an array, such as removing an element from a 1D array or removing rows and columns from a 2D array.
<br>

- ### If the axis is not specified, then the default axis 0 is considered.
<br>

- ### The delete() function can be used to modify the array, which can be helpful when we need to remove some elements from the array.
<br>

# Parameters
<br>

- ## arr Required
- ## obj Required
- ## axis Optional

In [1]:
import numpy as np

In [2]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.delete(arr=arr,obj=0) # return 1 D

array([2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.delete(arr=arr,obj=0,axis=0) # remove row with axis 0

array([[4, 5, 6],
       [7, 8, 9]])

In [5]:
np.delete(arr=arr,obj=0,axis=1) # remove column with axis 1

array([[2, 3],
       [5, 6],
       [8, 9]])

In [6]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.delete(arr=arr,obj=[0,4,8]) # reomve 1 ,5 ,9

array([2, 3, 4, 6, 7, 8])

In [8]:
np.delete(arr,np.s_[2:])

array([1, 2])

# we also use np._s[] for selecting specfic range

In [9]:
np.delete(arr,obj=np.s_[2:])

array([1, 2])

# *np.insert()*
<br>

- ### In NumPy, the insert() function is used to insert elements into an array. The syntax of this function is numpy.insert(arr, obj, values, axis=None), where arr is the input array, obj specifies the index or indices where the elements are to be inserted, values are the elements that will be inserted, and axis is an optional argument that specifies the dimension in which to insert the elements.
<br>

- ### By using the insert() function, we can insert elements into an array, such as inserting an element at a specific index in a 1D array or inserting elements into rows and columns in a 2D array.
<br>

- ### If the axis is not specified, the default axis is 0.
<br>

- ### By using the insert() function, we can modify an array, which can be very helpful when we need to insert some elements into an array.
<br>

# Parameters

- ## arr Required 
- ## obj Required
- ## values Optional
- ## axis Optional 

In [10]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [11]:
np.insert(arr=arr,obj=0,values=[0,0,0])

array([0, 0, 0, 1, 2, 3])

In [12]:
np.insert(arr=arr,obj=1,values=[0,0,0])

array([1, 0, 0, 0, 2, 3])

In [13]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.insert(arr=arr,obj=0,values=[0,0,0])

array([0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.insert(arr=arr,obj=0,values=[0,0,0],axis=0) # use axis 0 row

array([[0, 0, 0],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
# use np.s_
np.insert(arr=arr,obj=np.s_[0,1,2],values=[0,0,0],axis=0)

array([[0, 0, 0],
       [1, 2, 3],
       [0, 0, 0],
       [4, 5, 6],
       [0, 0, 0],
       [7, 8, 9]])

In [17]:
# use np.s_
np.insert(arr=arr,obj=np.s_[0,1,2],values=[0,0,0],axis=1)

array([[0, 1, 0, 2, 0, 3],
       [0, 4, 0, 5, 0, 6],
       [0, 7, 0, 8, 0, 9]])

# *np.append()*
<br>

- ### In NumPy, the append() function is used to add elements to an array. The syntax of this function is numpy.append(arr, values, axis=None), where arr is the input array, values are the elements that will be added, and the axis argument is optional and specifies the dimension to add the elements.
<br>

- ### By using the append() function, we can add elements to an array, such as adding a value to a 1D array, or adding elements to rows and columns in a 2D array.
<br>

- ### If the axis is not specified, the default value is None, which adds the values to the end of the array.
<br>

- ### Using the append() function, we can modify an array, which is very helpful when we need to add elements to an existing array.
<br>

# Parameter
<br>

- ## arr Required
- ## values Required
- ## axis Optional

In [18]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [19]:
np.append(arr=arr,values=[0,0,0])

array([1, 2, 3, 0, 0, 0])

In [20]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.append(arr=arr,values=[0,0,0])

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0, 0])

In [22]:
np.append(arr=arr,values=[[0,0,0]],axis=0) # now use the axis 0  for add 1 []

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 0, 0]])

In [23]:
np.append(arr=arr,values=[[0],[0],[0]],axis=1) 
# now use the axis 1 for add [] [] []  square brackets

array([[1, 2, 3, 0],
       [4, 5, 6, 0],
       [7, 8, 9, 0]])

# *np.trim_zeros()*
<br>

- ### In NumPy, the trim_zeros() function is used to remove zero values from an array. The syntax of this function is numpy.trim_zeros(arr, trim='fb'), where arr is the input array and trim is an optional argument that specifies whether to remove zero values from the beginning or end of the array.
<br>

- ### By using this function, we can remove zero values from an array, which reduces the size of the array and speeds up calculations.
<br>

# Parameters
<br>

- ## filt Required
- ## trim Optonal

In [24]:
arr = np.array([0, 0, 0, 1, 2, 3, 0, 0, 0])
arr

array([0, 0, 0, 1, 2, 3, 0, 0, 0])

In [25]:
np.trim_zeros(filt=arr)

array([1, 2, 3])

In [26]:
# 'f': Only trim zeros from the beginning (left) of the array.
np.trim_zeros(filt=arr,trim="f") 

array([1, 2, 3, 0, 0, 0])

In [27]:
# 'b': Only trim zeros from the end (right) of the array.
np.trim_zeros(filt=arr,trim="b") 

array([0, 0, 0, 1, 2, 3])

In [28]:
# 'fb': Trim zeros from both the beginning and end of the array (default behavior).
np.trim_zeros(filt=arr,trim="fb") 

array([1, 2, 3])