# NumPy is a powerful library for numerical computing in Python. It provides a variety of functions to create arrays of different shapes and sizes. Here are some of the most commonly used NumPy array creation functions

# Array Creations Functions
<br>

- ## Array creation functions create a new array from scratch.
<br>

- ## Array creation functions are used when you want to create a new array with specific dimensions and values

In [2]:
import numpy as np

<br>

- ## **np.empty()**
- ## **np.empty_like()**
- ## **np.eye()**
- ## **np.identity()**
- ## **np.onces()**
- ## **np.onces_like()**
- ## **np.zeros()**
- ## **np.zeros_like()**
- ## **np.full()**
- ## **np.full_like()**

<br>

# **np.empty()**
<br>

- ## The empty() function in NumPy library that creates an empty NumPy array with the size and shape you specify. When you use this function, the values in the array are not initialized or set to any specific value, and the array assumes some random values that were previously stored in the memory. 
<br>

- ## This function only allocates memory for the array and can be used to assign values to the array later as per your requirement.
<br>

- ## However, it's important to note that if you don't initialize the values of the array after creating it using this function, the array may contain unpredictable or random values, which may not be useful for your purpose.
<br>

## Parameters :

- ## shape required 
<br>

- ## dtype optional
<br>

- ## order optional (C,F)

In [14]:
shape = (2,2)
np.empty(shape)

array([[4.64714877e-310, 0.00000000e+000],
       [4.64775232e-310, 4.64775236e-310]])

In [20]:
np.empty(shape=(2,2),dtype=int)

array([[94059335034344,              0],
       [94071554975280, 94071554700896]])

In [66]:
np.empty(shape=(2,2),dtype=int,order="C")

array([[94059336737907,              0],
       [94071554975280, 94071554700896]])

In [65]:
np.empty(shape=(2,2),dtype=int,order="F")

array([[94059335574634, 94071554975280],
       [             0, 94071554700896]])

# **np.empty_like()**
<br>

- ## empty_like that creates a new array or data structure with the same shape and data type as a given array or data structure, but with all elements initialized to zero or empty.
<br>

# Parameters
<br>

- ## prototype, (Required)
<br>

- ## dtype=None,
<br>

- ## order='K', 
<br>

- ## subok=Tru

In [70]:
arr1 = np.array([1, 2, 3])
arr1

array([1, 2, 3])

In [78]:
arr2 = np.empty_like(arr1)
arr2

array([94059339087658,              0,             32])

# **np.eye()**
<br>

- ## The meaning of "eye()" function is an "identity matrix". This matrix has a value of 1 on its diagonal and all other values are 0.
<br>

- ## It is used to multiply any matrix by itself, and the output will be the original matrix. This matrix is important in matrix algebra and is often used in complex calculations.
<br>

# Parameters
<br>

- ## N required ROWS
- ## M optional COLUMNS
- ## K optional Dignol sequence position
- ## dtype optional
- ## order optional

In [3]:
np.eye(N=3,M=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.eye(N=3,M=3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [11]:
np.eye(N=6,M=4,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [6]:
row = 2
col = 4
np.eye(N=row,M=col)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

# **np.identity()**
<br>

- ## An identity matrix is a square matrix in which all the elements of the main diagonal are equal to 1 and all other elements are equal to 0. 
<br>

- ## This function is useful in linear algebra, where the identity matrix plays an important role in representing the identity transformation in vector spaces.
<br>

- ## Identity matrices are also useful in testing matrix operations and algorithms, as they have special properties that make them easy to work with.
<br>

# Parameters
<br>

- ## n Required (rowsxcolumn)
<br>

- ## dtype optional
    

In [12]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.identity(2,dtype=bool)

array([[ True, False],
       [False,  True]])

# **np.ones()**
<br>

- ## The ones function is used to create a new array of given shape and type, filled with ones.
<br>

- ## The ones() function is useful in situations where we need to create an array of ones with a specific shape and data type, for example in matrix operations or in initializing an array with default values.
<br>

# Parameters
- ## shape required
<br>

- ## dtype optional
<br>

- ## order optional

In [27]:
row = 3
col = 4
np.ones(shape=(row,col))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
np.ones(shape=(3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.ones(shape=(3))

array([1., 1., 1.])

# **np.ones_like()**
<br>

- ## The numpy.ones_like() function is used to create a new NumPy array filled with ones, where the shape and data type of the new array are the same as those of a given input array.
<br>

# Parameter
<br>

- ## a required
- ## dtype order
- ## order order
- ## subok order

In [37]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
np.ones_like(arr1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [39]:
np.ones_like(arr1,dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [41]:
np.ones_like(arr1,order="C")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [42]:
np.ones_like(arr1,subok=True)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [44]:
# change shape
np.ones_like(arr1,shape=(2,2))

array([[1, 1],
       [1, 1]])

# **np.zeros()**
<br>

- ## The numpy.zeros() function is used to create an array of specified shape and data type, filled with zeros.
<br>

- ## The function is commonly used to initialize an array of a specific size and type, before filling it with actual values obtained from some calculations or data sources. 
<br>

- ## It is also used as a placeholder to allocate memory for later use.
<br>

# Parameters
<br>

- ## shape required
- ## dtype optional
- ## order


In [3]:
np.zeros(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.zeros(shape=(3,3),dtype=bool) 

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [5]:
np.zeros(shape=(3))

array([0., 0., 0.])

In [6]:
np.zeros(shape=(3),order="C")

array([0., 0., 0.])

# **np.zeros_like()**
<br>

- ## The numpy.zeros_like() function takes an array_like object as input and returns an array of the same shape, size, and dtype with all elements set to zero.
<br>

- ## This function is useful when you want to create an array of zeros with the same shape and type as another array without explicitly specifying the shape and data type.
<br>

- ## It can also be used to initialize a new array with the same shape as an existing array but with all elements set to zero
<br>

# Parameters
<br>

- ## a required
- ## order optional
- ## subok optional

In [8]:
arr = np.arange(25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [9]:
np.zeros_like(arr)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [12]:
np.zeros_like(arr,dtype="bool")

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [13]:
np.zeros_like(arr,order="F")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# **np.full()**
<br>

- ## The numpy.full() function is used to create a new array of the specified shape and type, filled with a specified value.
<br>

# Parameters
<br>

- ## shape required
- ## fill_value required
- ## dtype optional
- ## order optional

In [4]:
np.full(shape=(3, 3),fill_value=5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [13]:
np.full(shape=(2,1),fill_value=10)

array([[10],
       [10]])

In [14]:
np.full(shape=(1,2),fill_value=10)

array([[10, 10]])

In [16]:
np.full(shape=(6,6),fill_value=-9)

array([[-9, -9, -9, -9, -9, -9],
       [-9, -9, -9, -9, -9, -9],
       [-9, -9, -9, -9, -9, -9],
       [-9, -9, -9, -9, -9, -9],
       [-9, -9, -9, -9, -9, -9],
       [-9, -9, -9, -9, -9, -9]])

In [17]:
np.full(shape=(6,6),fill_value=np.inf)

array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

# **np.full_like()**
<br>

- ## The numpy.full_like() function is used to create an array with the same shape as an existing array and fill it with a specific value.
<br>

# Parameters
<br>

- ## a    required
- ## full_value   required
- ## order
- ## subok

In [19]:
arr = np.zeros(shape=(3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.full_like(arr,fill_value=1)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])