# Broadcasting     

# The term broadcasting describe how numpy treats array with different shapes Durning Arithmetic Operations

# The Smaller array is broadcast across  the larger array so that they have compatible shapes

In [5]:
import numpy as np

In [2]:
a = np.arange(6).reshape(2,3)
b = np.arange(6).reshape(2,3)

In [3]:
print(a)

[[0 1 2]
 [3 4 5]]


In [4]:
print(b)

[[0 1 2]
 [3 4 5]]


In [5]:
# check shape
print(a.shape)
print(b.shape)

(2, 3)
(2, 3)


## Now we Easily Perform Operations like add divide etc

In [8]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
b

array([[0, 1, 2],
       [3, 4, 5]])

# Now Check with different shape of to array

In [11]:
a1 = np.arange(6).reshape(2,3)
b1 = np.arange(3).reshape(1,3)

a1

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
b1

array([[0, 1, 2]])

## Now it is possible to perfom operations ?


In [14]:
print(a1 + b1)

[[0 2 4]
 [3 5 7]]


## So How it is Possible ?

# This is the term of Broadcsting

# The term broadcasting describe how numpy treats array with **different** shapes Durning Arithmetic Operations

# The Smaller array is broadcast across  the larger array so that they have compatible shapes

# How its Work ?

<img src="../../images/broad.jpg" style="display: block;margin-left: auto;margin-right: auto;
  width: 80%; border-radius:0px 10px 10px 10px; height:80%;">


# Example 1

In [216]:
e1 = np.array([0,1,2])
e2 = np.array([5])


print(e1)
print(e2)

[0 1 2]
[5]


### Now when we try to perform the operations than small Demension array fill the the existing columns values

In [20]:
# means [5,5,5] when perform operations
# [0,1,2] + [5,5,5] = [5,6,7]

In [21]:
e1 + e2

array([5, 6, 7])

# Example 2

In [22]:
ex1 = np.ones((3,3))
ex2 = np.arange(3)

In [23]:
print(ex1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
print(ex2)

[0 1 2]


## now ex2 array fill its values

In [28]:
# [ [0,1,2 ]
# [ 0,1,2 ]
# [ 0,1,2] ]

In [29]:
ex1 + ex2

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

# Example 3 Intresting

In [32]:
exp1  = np.arange(3).reshape(3,1)
exp1

array([[0],
       [1],
       [2]])

In [34]:
exp2 = np.arange(3)
exp2

array([0, 1, 2])

In [35]:
print(exp1.shape)

(3, 1)


In [36]:
print(exp2.shape)

(3,)


## Now here is the best Sequence

In [39]:
# [0 1 2]
# --------------
# [0 1 2]
# [0 1 2]
# [0 1 2]

In [42]:
# [0,]
# [0,]
# [0,]
# -------------
# [0 1 2]
# [0 1 2]
# [0 1 2]


# now perform operations

In [45]:
exp1 + exp2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# How to work Broadcasting



# Rules

## NumPy broadcasting is the ability of NumPy to perform arithmetic operations between arrays with different shapes. When performing operations between arrays with different shapes, NumPy follows a set of broadcasting rules to determine how the operation should be carried out. Here are the rules:
<br>

- ## Two arrays are compatible for broadcasting if they have the same number of dimensions, and the size of each dimension in one array matches the size of the corresponding dimension in the other array, or if one of the arrays has a size of 1 in that dimension.
<br>
    
- ## If one array has fewer dimensions than the other, the missing dimensions are considered to have a size of 1. This is done by adding new dimensions with a size of 1 to the left of the smaller array's shape until it matches the number of dimensions in the larger array.

# Example

In [269]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [270]:
b = np.arange(3)
b

array([0, 1, 2])

# Step 1 Check Both Demension same ?
# if Demenstion are not same than increase Demension in smaller array

In [234]:
a.ndim

2

In [235]:
b.ndim

1

In [236]:
b

array([0, 1, 2])

In [240]:
temp_b = np.array([[0,1,2]])
temp_b

array([[0, 1, 2]])

In [241]:
temp_b.ndim

2

# Step 2 Check both shapes make sure in which right side of the shape are same or in which 1 array of the shape right side are 1 ?

In [242]:
a.shape

(4, 3)

In [243]:
temp_b.shape

(1, 3)

In [271]:
## (4,3) , (1,3) yes 3,3 are exist in both side
a + b

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [57]:
a + b

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [245]:
a + temp_b 

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

# Both result are same

# Example 2

In [296]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [297]:
b = np.arange(3)
b

array([0, 1, 2])

# Step 1 Check Both Demension same ?
# if Demenstion are not same than increase Demension in smaller array

In [275]:
a.ndim

2

In [276]:
b.ndim

1

In [277]:
# increase smaller array demension equal to target demension
b

array([0, 1, 2])

In [278]:
temp_b = np.array([[0,1,2]])
temp_b

array([[0, 1, 2]])

In [279]:
temp_b.ndim

2

# Step 2 Check both shapes make sure in which right side of the shape are same or in which 1 array of the shape right side are 1 ?

In [280]:
a.shape

(3, 4)

In [281]:
temp_b.shape

(1, 3)

In [298]:
# (3,4) , (1,3)  --> 4,3 both are not same so broadcasting not possible 
a + b

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

# Example 3

In [299]:
a = np.arange(3).reshape(1,3)
a 

array([[0, 1, 2]])

In [300]:
b = np.arange(3).reshape(3,1)
b

array([[0],
       [1],
       [2]])

# Step 1 Check Both Demension same ?
# if Demenstion are not same than increase Demension in smaller array

In [291]:
a.ndim

2

In [292]:
b.ndim

2

# Step 2 Check both shapes make sure in which right side of the shape are same or in which 1 array of the shape right side are 1 ?

In [301]:
a.shape

(1, 3)

In [302]:
b.shape

(3, 1)

In [303]:
# (1,3) (3,1) here 3,1 not same but 1 are include that means broadcasting are possible
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## Example 4

In [308]:
a = np.arange(3).reshape(1,3)
a

array([[0, 1, 2]])

In [309]:
b = np.arange(4).reshape(4,1)
b

array([[0],
       [1],
       [2],
       [3]])

# Step 1 Check Both Demension same ?
# if Demenstion are not same than increase Demension in smaller array

In [310]:
a.ndim

2

In [311]:
b.ndim

2

# Step 2 Check both shapes make sure in which right side of the shape are same or in which 1 array of the shape right side are 1 ?

In [312]:
a.shape

(1, 3)

In [313]:
b.shape

(4, 1)

In [314]:
# (1,3) (4,1) 3,1 both not same but 1 are include thats means broadcasting possible
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

# Example 5

In [317]:
a = np.array([1])
a

array([1])

In [318]:
b = np.arange(4).reshape(2,2)
b

array([[0, 1],
       [2, 3]])

# Step 1 Check Both Demension same ?
# if Demenstion are not same than increase Demension in smaller array

In [319]:
a.ndim

1

In [320]:
b.ndim

2

In [321]:
a

array([1])

In [322]:
# increase demension of smaller array
temp_a = np.array([[1]])
temp_a

array([[1]])

In [324]:
temp_a.ndim

2

# Step 2 Check both shapes make sure in which right side of the shape are same or in which 1 array of the shape right side are 1 ?

In [325]:
temp_a.shape

(1, 1)

In [326]:
b.shape

(2, 2)

In [327]:
# (1,1) (2,2) 1,2 not same but 1 are include
temp_a + b

array([[1, 2],
       [3, 4]])

In [329]:
a + b # both result are same

array([[1, 2],
       [3, 4]])

# Example 6

In [330]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [331]:
b = np.arange(4).reshape(2,2)
b

array([[0, 1],
       [2, 3]])

# Step 1 Check Both Demension same ?
# if Demenstion are not same than increase Demension in smaller array

In [332]:
a.ndim

2

In [333]:
b.ndim

2

# Step 2 Check both shapes make sure in which right side of the shape are same or in which 1 array of the shape right side are 1 ?

In [334]:
a.shape

(4, 4)

In [335]:
b.shape

(2, 2)

In [336]:
# (4,4) , (2,2) 4,2 not same and also 1 are not include thats means broadcasting are not possible
a + b

ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 