# Changing Shapes

- ## *np.resize()*
- ## *np.reshape()*
- ## *np.ravel()*
- ## *.flat*
- ## .flaten()

# Changing number of Dimensions

- ## *np.atleast_1d()*
- ## *np.atleast_2d()*
- ## *np.atleast_3d()*
- ## *np.expand_dims()*
- ## *np.squeeze()*
- ## *np.broadcast_array()*
- ## *np.broadcast()*
- ## *np.broadcast_to()*

# *np.resize()*

<br>

- ### In NumPy, the resize() function is used to change the size of an array. The syntax of this function is numpy.resize(arr, shape), where arr is the input array and shape is a tuple that specifies the desired size.
<br>

- ### By using the resize() function, we can modify the size of an array. If the desired size is smaller than the existing size, then the extra elements are cut off. And if the desired size is larger than the existing size, then the elements of the array are repeated.
<br>

- ### While the reshape() function is also used to modify the size of an array, it changes the dimensions of the array. By using the reshape() function, we can convert a 1D array into a 2D or 3D array. However, with the resize() function, we cannot change the dimensions of the array, only its size.
<br>

- ### Similarly, when modifying the size of an array using the reshape() function, if the product of the desired size and the existing size is not the same, then the reshape() function generates an error. But with the resize() function, we can set the size to any value without any error.

In [2]:
import numpy as np

In [3]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
arr.shape

(3, 2)

In [6]:
np.resize(a=arr, new_shape=(2,3))  # change shape

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.resize(a=arr, new_shape=(2,2))  # change shape now ignore elements

array([[1, 2],
       [3, 4]])

In [8]:
np.resize(a=arr, new_shape=(1,9))  # change shape repeating elements

array([[1, 2, 3, 4, 5, 6, 1, 2, 3]])

In [9]:
 np.resize(a=arr, new_shape=(1,6))  # change shape now ignore elements

array([[1, 2, 3, 4, 5, 6]])

In [11]:
## so we can't remove the Dimensions thats why we use reshape function

# *np.reshape()*
<br>

- ### Numpy's reshape() function is used to modify the shape of an existing array. This means that we can change the shape of an existing array.
<br>

- ### In this function, we need to provide the original array and the desired shape as arguments. We need to change the shape of the original array and define the dimensions of the new shape in the desired shape argument.
<br>

- ### The reshape() function is used for array manipulation. With this function, we can change the dimensions of an array, which allows us to work with data analysis and manipulation.
<br>

# Parameters
<br>

- ## a Required
- ## newshape Required
- ## order Optional

In [2]:
array = np.array([1,2,3,4,5,6])
array

array([1, 2, 3, 4, 5, 6])

In [3]:
# checking shape
array.shape

(6,)

In [4]:
new = np.reshape(a=array,newshape=(3,2)) # 3 * 2 = 6
new

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
# check new shape
new.shape

(3, 2)

In [6]:
np.reshape(a=array,newshape=(3,-1)) # -1 AUTO adjust array shape

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
np.reshape(a=array,newshape=(3,2),order="F")

array([[1, 4],
       [2, 5],
       [3, 6]])

In [8]:
np.reshape(a=array,newshape=(3,2),order="A") # C,F,A,K VALID ORDERS

array([[1, 2],
       [3, 4],
       [5, 6]])

# *np.ravel()*
<br>

- ### In NumPy, ravel() is a function that helps us to flatten the elements of an existing array into a one-dimensional array. This means that we can arrange the elements of an existing array into a single line.
<br>

- ### Both the reshape() and ravel() functions are used in array manipulation. However, their main difference is that the reshape() function helps us to modify the shape of the array, while the ravel() function helps us to flatten the elements of the array. The ravel() function does not create a copy of the array but directly flattens the elements of the array.
<br>

- ### The ravel() function is used in data analysis where we need a one-dimensional array.
<br>

# Parameters
<br>

- ## a Requird
- ## order Optional


In [9]:
# 3D array
arr = np.array([[[1,2,3]]])
arr

array([[[1, 2, 3]]])

In [10]:
# check dim
arr.ndim

3

In [11]:
# use raval
reduce = np.ravel(arr)
reduce

array([1, 2, 3])

In [12]:
reduce.ndim # check dim

1

In [13]:
np.ravel(np.array([ [1,2,3], [4,5,6] ]))

array([1, 2, 3, 4, 5, 6])

In [14]:
np.ravel(np.array([ [1,2,3], [4,5,6] ]),order="F")

array([1, 4, 2, 5, 3, 6])

In [15]:
np.ravel(-1)

array([-1])

- ### The NumPy ndarray.flat() function is similar to the ravel() function in that it helps us flatten an existing array's elements into a one-dimensional array. This means we can arrange all the elements of an array in a single line.
<br>

- ### However, the major difference between ndarray.flat() and ravel() is that the former returns the array's elements as an iterator object that we can reshape later. This means we can perform any operation with this iterator object and then reshape it.
<br>

- ### Both ravel() and ndarray.flat() functions are useful for flattening the elements of an array. However, ravel() function directly flattens the elements of an array without making a copy. In contrast, the ndarray.flat() function returns an iterator object that can be reshaped later.
<br>

- ### This function is also useful in data analysis where we require a one-dimensional array and need to reshape the elements of an array.

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7 ,8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
iterable = arr.flat
iterable # now array are iterable

In [18]:
len(iterable)

9

In [19]:
for i in iterable:
    print(i)

1
2
3
4
5
6
7
8
9


In [20]:
# traversing without using .flat
for i in arr:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


# *.flatten()*
<br>

- ### The NumPy function ndarray.flatten() helps us to flatten the elements of an existing array into a one-dimensional array, just like the ravel() and ndarray.flat functions. This means that we can arrange all the elements of an existing array together in a line.
<br>

- ### However, the major difference with ndarray.flatten() is that it returns a new array in flattened form, while ndarray.flat returns an iterator object.
<br>

- ### ndarray.flatten() creates a copy of the original array and flattens its elements into a new array. This means that there are no changes to the original array. On the other hand, ndarray.flat() flattens the elements of the original array, so if we make any changes to the iterator object, those changes will be reflected in the original array as well.
<br>

- ### Both functions are used for flattening array elements, but they return different objects. If we need a one-dimensional array, then ndarray.flatten() function is very useful.
<br>

# Parameter
<br>

- ## order optional

In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7 ,8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr.flatten(order="F")

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [24]:
for i in arr.flatten():
    print(i)

1
2
3
4
5
6
7
8
9


# *np.atleast_1d()*
<br>

- ### NumPy's atleast_1d() function is used to convert the input into at least a one-dimensional array. If the input is already a one-dimensional array, the function does not modify it and returns it as is. However, if the input is a scalar or a sequence, the function converts it into a one-dimensional array.
<br>

- ### This means that we do not need to worry about the shape of the input and can always use atleast_1d() function to convert it into a one-dimensional array.
<br>

# Parmeters
<br>

- ## *args

In [25]:
arr = np.array(100)
arr

array(100)

In [26]:
# check dim
arr.ndim

0

In [27]:
np.atleast_1d(arr)

array([100])

In [28]:
np.atleast_1d(1,2,3) # now return list in which arr elements are 1 d array

[array([1]), array([2]), array([3])]

# *np.atleast_2d()*
<br>

- ### In NumPy, atleast_2d() is a function that helps us to convert the input into at least a two-dimensional array. If the input is already a two-dimensional array, this function does not modify it and returns it as it is. However, if the input is a scalar or a one-dimensional array, then this function converts it into a two-dimensional array.
<br>

- ### This means that we do not need to worry about the shape of the input and can always use atleast_2d() function to convert the input into a two-dimensional array.
<br>

# Parameters
<br>

  - ## *args

In [29]:
arr = np.atleast_2d([1,2,3])
arr

array([[1, 2, 3]])

In [30]:
arr.ndim

2

In [31]:
np.atleast_2d(1,2,3) # now return list in which all elements are 2 d array

[array([[1]]), array([[2]]), array([[3]])]

# *np.atleast_3d()*
<br>

- ### The numpy.atleast_3d() function is used to convert the input into a 3-dimensional array, even if it has fewer dimensions. If the input is already a 3-dimensional array, then it is returned as it is, without any modifications. However, if the input is a scalar or a 1-dimensional or 2-dimensional array, then it is converted into a 3-dimensional array.
<br>

- ### This is useful when we want to perform operations on a 3-dimensional array but we are not sure if the input is already in that format or not. We can use numpy.atleast_3d() function to ensure that the input is in the required format.
<br>

# Parameters
<br>

- ## *args

In [32]:
arr = np.array(100)
arr

array(100)

In [33]:
np.atleast_3d(arr)

array([[[100]]])

In [34]:
np.atleast_3d(1,2,3) # now return list in which all elements are 3 d array

[array([[[1]]]), array([[[2]]]), array([[[3]]])]

# *np.expand_dims()*
<br>

- ### The numpy.expand_dims() function is used to add an extra dimension to an array. It takes the array and the axis as arguments and returns a new array with the specified dimension added. This function can be useful in situations where an operation requires arrays with matching dimensions.
<br>

# Parameters
<br>

- ## a  Required
- ## axis Required

In [35]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [36]:
# check dim
a.ndim

1

In [37]:
np.expand_dims(a=a,axis=0)

array([[1, 2, 3]])

In [38]:
np.expand_dims(a=a,axis=1)

array([[1],
       [2],
       [3]])

# *np.squeeze()*
<br>

- ### The numpy.squeeze() function is used to reduce or remove dimensions from any array. If any dimension of an array has a size of 1, it means that the values in that dimension are the same across all elements, and removing that dimension will not affect the values of the array.
<br>

- ### The use of the numpy.squeeze() function is when we need to provide an input array for a function or operation but do not require any dimensions.
<br>

# Parameter
<br>

- ## a Required
- ## axis optional

In [39]:
arr = np.array([[[1], [2], [3]], [[4], [5], [6]]])

In [40]:
arr

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [41]:
# check ndim 
arr.ndim

3

In [42]:
# reduce 1 dim

new = np.squeeze(arr)
new

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
# now check dim

new.ndim

2

# np.bradcast_arrays()
<br>

- ### np.broadcast_arrays() is a NumPy function that broadcasts any number of input arrays against each other, in a way that they all have the same shape. This can be useful when we want to perform arithmetic or other operations on arrays with different shapes.
<br>

- ### The np.broadcast_arrays() function returns a tuple of the broadcasted arrays, which can be used for further calculations. It is important to note that this function does not create new arrays, but rather creates a view of the input arrays with broadcasted shapes.
<br>

- ### The broadcasting rules in NumPy can be a bit complex, especially when dealing with arrays with different numbers of dimensions. The np.broadcast_arrays() function simplifies this process by automatically broadcasting the arrays to have the same shape, regardless of their initial shape.
<br>

- ### Overall, the np.broadcast_arrays() function can be very useful for performing operations on arrays with different shapes, without having to manually reshape or broadcast them.

In [44]:
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])

In [45]:
a

array([1, 2, 3])

In [46]:
b

array([[1],
       [2],
       [3]])

In [47]:
np.broadcast_arrays(a,b) # now we easily perform the opertions

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]),
 array([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])]

In [48]:
x,y = np.broadcast_arrays(a,b) # split both arrays

In [49]:
x

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [50]:
y

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [51]:
x + y

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

## but why we use np.broadcast_arrays() ? 

In [52]:
a + b # means a + b python perform the automatic broadcast the arrays

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

- ## NumPy automatically broadcasts arrays in many cases when you perform element-wise operations, like addition, subtraction, multiplication, etc. In such cases, you might not need to explicitly use `np.broadcast_arrays()`.
<br>

## However, there are situations where `np.broadcast_arrays()` can be helpful ?
<br>

- ### 1. Memory efficiency: When using np.broadcast_arrays()`, the returned broadcasted arrays share the same underlying data as the input arrays, which can save memory. This can be useful when working with large arrays.
<br>

- ### 2. Consistency in shape: If you want to ensure that multiple arrays have the same shape before performing an operation, using `np.broadcast_arrays() can help you achieve that. It returns arrays with the same shape as the result of broadcasting, making it easy to check that your arrays are compatible.
<br>

- ### 3. Complex operations: When you have more complex operations involving multiple arrays, or when you want to perform multiple operations on arrays with different shapes, using `np.broadcast_arrays() can simplify your code and make it easier to understand.
<br>

- ### 4. Custom functions: If you are implementing custom functions that involve element-wise operations, using `np.broadcast_arrays() can help make your code more robust by handling the broadcasting step explicitly, rather than relying on NumPy's automatic broadcasting.
<br>

- ### In summary, while NumPy does broadcast arrays automatically in many cases, using np.broadcast_arrays() can provide additional benefits, such as memory efficiency, shape consistency, simplification of complex operations, and improved robustness in custom functions.

In [53]:
# example 2

x = np.array([1,2,3])
y = np.array([[1],[2],[3],[4],[5]])

In [54]:
x.shape

(3,)

In [55]:
y.shape

(5, 1)

In [56]:
print(x)
print()
print(y)

[1 2 3]

[[1]
 [2]
 [3]
 [4]
 [5]]


In [57]:
br_x, br_y = np.broadcast_arrays(x,y)

In [58]:
print(br_x)
print()
print(br_y)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]]


In [59]:
br_x + br_y

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8]])

# *np.broadcast()*
<br>

- ### The numpy.broadcast() function in NumPy is used to broadcast two arrays. This function provides information about the broadcastable arrays. Broadcasting is a process of comparing the dimensions of two arrays and if they are compatible, operations are performed.
<br>

- ### Broadcasting simplifies array operations and makes the code more efficient. The syntax of the numpy.broadcast() function is numpy.broadcast(shape_x, shape_y, …), where shape_x, shape_y, … are the shapes of input arrays. The output of this function is a broadcast object that stores information about the broadcastable arrays.
<br>

- ### We can perform operations on broadcastable arrays using the output of the numpy.broadcast() function, such as addition, multiplication, etc. In these operations, numpy broadcasting rules are applied by comparing the dimensions of the two arrays and if they are compatible, operations are performed.
<br>

- ### A numpy broadcast object is used in such operations, which is created using the numpy.broadcast() function. Broadcasting is very important in NumPy for performing vectorized operations.

In [74]:
a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])

broadcast_obj = np.broadcast(a, b)

broadcast_obj

In [75]:
# convert into list
list(broadcast_obj)

[(1, 4), (2, 4), (3, 4), (1, 5), (2, 5), (3, 5), (1, 6), (2, 6), (3, 6)]

In [76]:
#check shape
broadcast_obj.shape

(3, 3)

In [89]:
# now use the broadcast_obj

result = np.zeros(broadcast_obj.shape,dtype=int) 
result 

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [90]:
for (i,j), _ in np.ndenumerate(result):
#     print(i,j) # split 0.0 inside _
    print(result[i,j],a[i],b[i]) 

0 1 [4]
0 1 [4]
0 1 [4]
0 2 [5]
0 2 [5]
0 2 [5]
0 3 [6]
0 3 [6]
0 3 [6]


In [91]:
for (i, j), _ in np.ndenumerate(result):
    result[i, j] = a[i] + b[j]  # perform add operation and save in result

In [92]:
result

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [93]:
# Now use broadcast_arrays()
x , y = np.broadcast_arrays(a,b)

In [94]:
x + y

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [96]:
a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])

broadcast_obj = np.broadcast(a, b)
result = np.zeros(broadcast_obj.shape,dtype=int)

for (i, j), _ in np.ndenumerate(result):
    result[i, j] = a[i] + b[j] 

x , y = np.broadcast_arrays(a,b)
print(x + y)
print()
print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]

[[5 6 7]
 [6 7 8]
 [7 8 9]]


## Differences
<br>

- ### The np.broadcast() function compares the shapes of input arrays to provide information about broadcastable arrays. The output of this function is a broadcast object that is used for broadcasting. The shape of the output object created by np.broadcast() function is the **(maximum shape)** of all input arrays. This shape is used for broadcastable arrays.
<br><br>

- ### The np.broadcast_arrays() function is used to create broadcastable arrays. If the shape of an input array is not broadcastable, we can use this function to change its shape and make it broadcastable. The output of this function is broadcastable arrays, whose shape is determined by taking the **(maximum dimensions)** of the input arrays.
<br><br>

- ### When we use the np.broadcast() function, we use the broadcast object to perform operations. However, after using the np.broadcast_arrays() function, we modify the input arrays to create broadcastable arrays and then perform operations on them.
<br>

- ### In summary, the np.broadcast() function provides information about broadcastable arrays, while the np.broadcast_arrays() function is used to create broadcastable arrays.
<br><br>

# *np.broadcast_to()*
<br>

- ### The NumPy broadcast_to() function is used to broadcast an array into a specified shape. The syntax for this function is numpy.broadcast_to(array, shape, subok=False), where the array is the input array to broadcast and shape is the broadcast shape. If subok=True, then this function will return any view of the input array, but if subok=False, then this function always creates a copy.
<br><br>
# Differences
<br><br>

- ### Broadcasting is used to perform operations between multiple arrays. The numpy.broadcast() function compares the shapes of input arrays and provides information about broadcastable arrays. This function returns a broadcast object, which is used for broadcasting. The shape of the output object of this function is the maximum shape of all input arrays, which is used for broadcastable arrays.
<br>

- ### The numpy.broadcast_to() function broadcasts a single array into a specified shape, while np.broadcast() function is used to convert multiple arrays into a broadcastable shape. Therefore, the use of both functions in broadcasting operations is different.

In [148]:
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])

In [126]:
np.broadcast_to(b ,(3, 3))

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [134]:
np.broadcast_to(a ,(3, 3))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [140]:
a

array([1, 2, 3])

In [143]:
np.broadcast_to(a ,(1, 3))

array([[1, 2, 3]])

In [144]:
np.broadcast_to(a ,(2, 3))

array([[1, 2, 3],
       [1, 2, 3]])

In [145]:
np.broadcast_to(a ,(3, 3))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [147]:
np.broadcast_to(a ,(6, 3))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])