# NumPy data types are useful in several ways

<br>

# Memory efficiency
<br>

- ## NumPy's array data structure allows for efficient storage of large amounts of data in memory, making it ideal for working with large datasets.
<br>

# Mathematical operations
<br>

- ## NumPy's array data structure and functions are optimized for performing mathematical operations on large arrays, making it faster and more efficient than using traditional Python lists.
<br>

# Integration with other libraries 
<br>

- ## NumPy is a widely used library in the scientific Python ecosystem and is often used in conjunction with other libraries such as SciPy, Pandas, and Matplotlib.
<br>

# Machine learning
<br>

- ## Many machine learning algorithms require data to be in a specific format, such as arrays of a particular data type. NumPy provides tools for manipulating and transforming data to be used in machine learning algorithms.
<br>

# Overall, NumPy's data types are useful for anyone working with numerical data and require fast and efficient computations. It is widely used in data analysis, scientific computing, and machine learning.

<br>

# Data Types

<br>

- ## np.bool_
## Type  : Boolean stored as a byte.
## Range : True or False

In [20]:
import numpy as np
import sys

In [2]:
np.array([0,1,2])

array([1, 2])

In [10]:
np.array([0,1,2],dtype=np.bool_)

array([False,  True,  True])

- ## np.int_
## Type  : Default integer type. 
## Range : Same as C long; normally either int64 or int32.

In [28]:
r = np.array([0,1,2],dtype=np.int_)
print(r)
print(sys.getsizeof(r))

[0 1 2]
136


- ## np.intc
## Type  : Identical to C int. 
## Range :  Normally int32 or int64.

In [29]:
r = np.array([0,1,2],dtype=np.intc)
print(r)
print(sys.getsizeof(r))

[0 1 2]
124


- ## np.intp
## Type  : Integer used for indexing. 
## Range :  Same as C ssize_t; normally either int32 or int64.

In [30]:
r = np.array([0,1,2],dtype=np.intp)
print(r)
print(sys.getsizeof(r))

[0 1 2]
136


- ## np.int8
## Type  : Byte. 
## Range : -128 to 127

In [43]:
r = np.array([0,1,2],dtype=np.int8)
print(r)
print(sys.getsizeof(r))

[0 1 2]
115


- ## np.int16
## Type  : Integer. 
## Range :  -32768 to 32767

In [44]:
r = np.array([0,1,2],dtype=np.int16)
print(r)
print(sys.getsizeof(r))

[0 1 2]
118


- ## np.int32

## Type  : Integer. 
## Range : -2147483648 to 2147483647

In [45]:
r = np.array([0,1,2],dtype=np.int32)
print(r)
print(sys.getsizeof(r))

[0 1 2]
124


- ## np.int64
## Type  : Integer. 
## Range : -9223372036854775808 to 9223372036854775807 

In [46]:
r = np.array([0,1,2],dtype=np.int64)
print(r)
print(sys.getsizeof(r))

[0 1 2]
136


- ## np.uint8
## Type  : Unsigned integer. 
## Range :  0 to 255

In [47]:
r = np.array([0,1,2],dtype=np.uint8)
print(r)
print(sys.getsizeof(r))

[0 1 2]
115


- ## np.uint16
## Type  : Unsigned integer. 
## Range :   0 to 65535

In [48]:
r = np.array([0,1,2],dtype=np.uint16)
print(r)
print(sys.getsizeof(r))

[0 1 2]
118


- ## np.uint32
## Type  : Unsigned integer. 
## Range :   0 to 4294967295

In [50]:
r = np.array([0,1,2],dtype=np.uint32)
print(r)
print(sys.getsizeof(r))

[0 1 2]
124


- ## np.uint64
## Type  : Unsigned integer. 
## Range :  0 to 18446744073709551615

In [51]:
r = np.array([0,1,2],dtype=np.uint64)
print(r)
print(sys.getsizeof(r))

[0 1 2]
136


- ## np.float16
## Type  : Half precision float. 
## Range :  sign bit, 5 bits exponent, 10 bits mantissa 

In [54]:
r = np.array([0,1,2],dtype=np.float16)
print(r)
print(sys.getsizeof(r))

[0. 1. 2.]
118


- ## np.float32
## Type  : Single precision float. 
## Range :  sign bit, 8 bits exponent, 23 bits mantissa 

In [56]:
r = np.array([0,1,2],dtype=np.float32)
print(r)
print(sys.getsizeof(r))

[0. 1. 2.]
124


- ## np.float64
## Type  : Double precision float. 
## Range :  sign bit, 11 bits exponent, 52 bits mantissa 

In [57]:
r = np.array([0,1,2],dtype=np.float64)
print(r)
print(sys.getsizeof(r))

[0. 1. 2.]
136


- ## np.comple64
## Type  : Complex. 
## Range :   two 32-bit floats (real and imaginary components)

In [59]:
r = np.array([0,1,2],dtype=np.complex64)
print(r)
print(sys.getsizeof(r))

[0.+0.j 1.+0.j 2.+0.j]
136


- ## np.comple128
## Type  : Complex. 
## Range :  two 64-bit floats (real and imaginary components)

In [60]:
r = np.array([0,1,2],dtype=np.complex128)
print(r)
print(sys.getsizeof(r))

[0.+0.j 1.+0.j 2.+0.j]
160


# Memory Efficiency and Storage

## normal list 

In [73]:
import time
t = time.time()
a = [i for i in range(100000000)]
print(time.time()-t)

2.9726221561431885


# with Numpy

In [74]:
t = time.time()
a = np.arange(100000000)
print(time.time()-t)

0.9253377914428711


# Compare Size

In [83]:
a = [i for i in range(100000000)]
print(len(a))
print(sys.getsizeof(a))

100000000
835128600


In [84]:
a = np.arange(100000000)
print(len(a))
print(sys.getsizeof(a))

100000000
800000112


## we also set the data dtype

In [92]:
a = np.arange(100000000,dtype=np.int8)
print(len(a))
print(sys.getsizeof(a))

100000000
100000112
