# Existing array creation functions create a new array based on an existing array
<br>

- ## existing array creation functions are used when you want to manipulate an existing array in some way to create a new array.
    

## Difference Array Creation Function VS Existing Array Function

<br>

- ## The main difference between these two categories is that array creation functions create a new array from scratch, while existing array creation functions create a new array based on an existing array. 
<br>

- ## For example, if you want to change a value in an array or combine some values to create a new array, you can use existing array creation function. 
<br>

- ## However, if you want to create a new array with specific dimensions and values, you can use array creation function.

- ## *np.array()*
- ## *np.asarray()*
- ## *np.asanyarray()* 
- ## *np.ascontiguousarray*
- ## *np.asmatrix()*
- ## *np.copy()*
- ## *np.fromfunction()*
- ## *np.fromiter()*

# *np.array()*
<br>

- ## The numpy.array() function is used to create an array. This function takes an iterable object as input and returns a new NumPy array with a specified data type (if provided) and shape.
<br>

- ## The array() function is useful when working with data that can be converted into an array, such as a list of numbers. It is often used to create a NumPy array from an existing Python list or tuple.
<br>

# Parameters
<br>

- ## object required
- ## dtype optional
- ## copy  optional
 - ### If true (default), then the object is copied. Otherwise, a copy will only be made
- ## order optional (K,A,C,F)
- ## ndmin optional


In [1]:
lst = [1,2,3,4,5,6,7,8,9]
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [1]:
import numpy as np

np.array(lst)

NameError: name 'lst' is not defined

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [5]:
np.array([1,2,3],ndmin=2)

array([[1, 2, 3]])

In [7]:
np.array([1,2,3],ndmin=20)

array([[[[[[[[[[[[[[[[[[[[1, 2, 3]]]]]]]]]]]]]]]]]]]])

In [8]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

# *np.asarray()*
<br>

- ## The numpy.asarray() function is used to convert a given input to an array.
<br>

- ## This is useful when the input may be a list or a tuple, which cannot be used in array-specific operations
<br>

- ## asarray() function, we need to specify an existing array

# Parameters
<br>

- ## a Required
- ## dtype optional
- ## order optional 

In [15]:
arr

array([1, 2, 3])

In [16]:
x = np.asarray(arr)*2
x

array([2, 4, 6])

In [17]:
y = arr * 2
y

array([2, 4, 6])

## whats is the difference in x and y means array() vs asarray() both are same ?

- ## np.asarray() function is used to convert the input to an array, and if the input is already an array, it returns the same array without creating a new one.

<br>

# *np.asanyarray()*
<br>

- ## The asanyarray() function in NumPy is similar to the asarray() function, but with some additional functionality. 
<br>

- ## The asanyarray() function also converts input to an ndarray, but it leaves subclasses of ndarray unchanged. If the input is already an ndarray or a subclass of ndarray, then asanyarray() simply returns the input. 
<br>

- ## However, if the input is a Python sequence or a subclass of Python sequence, it will be converted to an ndarray.
<br>

# Parameters
<br>

- ## a Required
- ## dtype
- ## order

In [18]:
def my_func(arr):
    arr = np.asanyarray(arr)
    # Perform some operations on the input array
    return arr

In [21]:
# Input can be a NumPy array or any array-like object
a = [1, 2, 3]
b = np.array([4, 5, 6])

# Call the function with different inputs
print(my_func(a))  # Output: [1 2 3]
print(my_func(b))  # Output: [4 5 6]


[1 2 3]
[4 5 6]


## Example 2

In [26]:
def increment(arr):
    return np.asanyarray(arr) + 1 

In [27]:
ar = np.array([1,2,3])
ar

array([1, 2, 3])

In [28]:
increment(ar)

array([2, 3, 4])

# *np.ascontiguousarray()*
<br>

- ### The "numpy.ascontiguousarray() function" is used to convert the memory layout of an array into a contiguous layout. This function allows us to organize any array into a contiguous memory layout, which can improve its access speed.
<br>

- ### When an array's values are stored together in memory, it is called a contiguous layout. However, if the values are stored in different memory locations, it is called a non-contiguous layout, which can result in slower access speeds. Therefore, the ascontiguousarray() function is used to improve the performance of an array.
<br>

- ### This function is used without copying the data, and if the array is already in a contiguous layout, it will be returned as it is. It is often used when working with large datasets and when we need to improve the performance of an array.
<br>

# Parameters
<br>

- ## a Required
- ## dtype optional

In [50]:
# create a non-contiguous 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
arr

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [40]:
print("Original array:")
print(arr)
print("\nStride of the original array:")
print(arr.strides)

Original array:
[[1 2 3]
 [4 5 6]]

Stride of the original array:
(12, 4)


In [49]:
# contiguousarray
cont_arr = np.ascontiguousarray(arr, dtype=np.int32)
cont_arr

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [48]:
print("Contiguous array:")
print(cont_arr)
print("\nStride of the contiguous array:")
print(cont_arr.strides)

Contiguous array:
[[1 2 3]
 [4 5 6]]

Stride of the contiguous array:
(12, 4)


# *np.asmarix()*
<br>

- ### The "asmatrix()" function in NumPy is used to treat 2D arrays like matrices. This function treats a 2D array as a matrix and provides matrix operations and functionality.
<br>

- ### When we need to perform matrix operations such as matrix multiplication, transpose, inverse, determinant, etc., we use the asmatrix() function. This function converts a 2D array into a matrix and allows us to perform all operations with matrices.
<br>

- ### When using this function, we can also index the rows and columns of the 2D array. Using this function, we can optimize our code and use built-in functions and operations to perform all operations with matrices.
<br>

# Parameters
<br>

- ## data Required
- ## dtype optional

In [51]:
# creating a 2D array
arr = np.array([[1, 2], [3, 4]])
arr

array([[1, 2],
       [3, 4]])

In [52]:
# converting the 2D array to matrix
mat = np.asmatrix(arr)
mat

matrix([[1, 2],
        [3, 4]])

In [53]:
# performing matrix multiplication
mul = mat * mat
mul

matrix([[ 7, 10],
        [15, 22]])

In [55]:
# now same operation with array
arr * arr

array([[ 1,  4],
       [ 9, 16]])

# np.copy()
<br>

- ## The numpy.copy() function is used to get an array copy of an given object.
<br>

- ### The copy() function can be useful when you want to make changes to an array without modifying the original array. 
<br>

- ### For example, if you want to perform a series of operations on an array and keep the original array intact, you can create a copy of the original array using the copy() function and perform the operations on the copy. 
<br>

- ### This can also be useful when you want to pass a copy of an array to a function without modifying the original array.
<br>

# Parameters
<br>

- ## a Required
- ## order optional

In [56]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [57]:
temp = arr
temp

array([1, 2, 3])

In [58]:
## now change in temp
temp += 1
temp

array([2, 3, 4])

In [59]:
## now check orignal array
arr

array([2, 3, 4])

In [60]:
# use copy
tmp = arr.copy()

In [61]:
print(arr)
print(tmp)

[2 3 4]
[2 3 4]


In [62]:
# now changes in tmp 
tmp += 1
tmp

array([3, 4, 5])

In [63]:
## check orignal array
arr

array([2, 3, 4])

# *np.fromfunction()*
<br>

- ### The "numpy.fromfunction()" function is used to create a new ndarray from the output of a user-defined function. This function takes a user-defined function as input, which calculates an output value using the input shape and index. Then this function creates a new ndarray from these output values.
<br>

- ### This function is generally used for large datasets, where it is not possible to manually generate data. With the help of this function, we can generate data using a user-defined function that satisfies our data requirements.
<br>

- ### By using this function, we do not need to manually generate data, and we can obtain data generated using a user-defined function. This function is very useful, especially in fields such as scientific computing and machine learning, where data generation is required.
<br>

# Parameters
<br>

- ## function Required
- ## shape Required
- ## dtype optional


In [66]:
def generate(i, j):
    return (i+1)*(j+1)

In [68]:
generate(5,2) # 6 * 2 = 12

18

In [70]:
# now use in numpy
np.fromfunction(generate,shape=(5,2))

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.]])

# *np.fromiter()*
<br>

- ### The "numpy.fromiter()" function is used to create a new ndarray from an iterator. In this function, we take an iterator as input and create a new ndarray from its elements.
<br>

- ### This function is generally used to read data from an existing sequence or data source. Using an iterator to read data has the advantage of improving memory consumption and the overall performance of the program.
<br>

- ### With the help of this function, we can read data from any iterable object, such as a file, list, tuple, generator, etc. This function is an efficient way to read data, especially when working with large datasets.
<br>

- ### When using this function, we need to specify the data type of the iterator's elements so that the function knows which type of values to read.
<br>

# Parameters
<br>

- ## iterable Required
- ## dtype Required
- ## count optional



In [71]:
lst = [1,2,3,4,5,6,7,8]
lst

[1, 2, 3, 4, 5, 6, 7, 8]

In [74]:
np.fromiter(iter=lst,dtype=int)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
np.fromiter(iter=lst,dtype=int,count=5)

array([1, 2, 3, 4, 5])

- ### We use np.fromiter() function to create a new NumPy array from an iterable object like a file, list, tuple, or generator. This function provides an efficient way to read data from the iterable object and create a NumPy array without reading the entire object into memory at once.
<br>

- ### By using np.fromiter(), we can process data in a stream-like fashion, one element at a time, which helps to reduce memory consumption and improve overall program performance, especially when dealing with large datasets.
<br>

- ### Additionally, we can specify the data type of the elements in the iterable object, which allows NumPy to create a new array with the desired data type. This function is particularly useful when working with data from an external source where we need to read the data in chunks and process it on the fly
<br>

# Parameters
<br>

- ## string Required
- ## dtype optional
- ## count optional
- ## sep optional

# *np.fromstring()*
<br>

- ### The "np.fromstring()" function is a NumPy library function used to create a NumPy array from a string. In this function, we provide a string as input, whose format is in a specified data type format, such as integer, float, etc.
<br>

- ### This function is very useful when we have data available in a string format and we want to convert that data into a NumPy array format. When using this function, we need to specify the format and data type of the string, so that the function knows how to convert the data.
<br>

- ### We also need to specify the encoding of the string in this function, such as ASCII, Unicode, etc. By using this function, we can convert data available in any string format into a NumPy array format, allowing us to easily manipulate the data, such as slicing, indexing, mathematical operations, etc.

In [80]:
st = "1,2,3,4,5"
st

'1,2,3,4,5'

In [85]:
np.fromstring(st,dtype=int,sep=",")

array([1, 2, 3, 4, 5])

In [86]:
np.fromstring(st,dtype=int,sep=",",count=3)

array([1, 2, 3])