- ## *np.where()*
- ## *np.extract()*
- ## *np.compress()*
- ## *np.take()*
- ## *np.put()*
- ## *np.clip()*
- ## *np.putmask()*
- ## *np.unique()*
- ## *np.nonzero()*

# *np.where*

<br>

- ### The numpy.where() function is a part of the NumPy library in Python, which is used for condition-based filtering of elements in an array.
<br>

- ### With the help of this function, we can filter out the elements from an array based on a given condition. The numpy.where() function accepts three arguments:
<br>

- ### condition: This argument is the condition based on which we want to filter the elements of the array.
<br>
    
- ### x: This argument is the array from which we want to filter the elements based on the condition.
<br>

- ### y: This argument is the array from which we want to filter the elements against the condition.
<br>

- ### As the name suggests, in the numpy.where() function, we specify two values against the condition, and the function selects either one of them based on the condition.
<br>

- ### The output of this function is an array that contains the filtered elements.
<br>

- ### The numpy.where() function is widely used in various data analysis tasks, such as data filtering, data cleaning, and data manipulation, as it allows us to easily filter the elements of an array and modify them according to our needs.

In [1]:
import numpy as np

In [2]:
data = np.array([0,1,0,0,2,3,4])
data

array([0, 1, 0, 0, 2, 3, 4])

In [3]:
np.where(data==0,1,data) # replace 0 to 1 if data is 0

array([1, 1, 1, 1, 2, 3, 4])

In [4]:
data = np.array([0,1,1,2,0,3,4])
data

array([0, 1, 1, 2, 0, 3, 4])

In [5]:
np.where(data==0,8, np.where(data==1,9,data)  ) # replace 0 with 8 and 1 replace with 9

array([8, 9, 9, 2, 8, 3, 4])

In [6]:
condition = (data==0) | (data == 1) 
np.where(condition,888,data)  # apply multiple condition  replace 0 and 1 with 888

array([888, 888, 888,   2, 888,   3,   4])

# *np.extract()*
<br>

- ### The numpy.extract() function is used to directly filter the elements of an array, without any condition.
<br>

- ### In this function, we pass only one argument which gives us the array from which we want to filter the elements. Then, we provide a condition inside the numpy.extract() function which tells us how we want to filter the elements.
<br>

- ### The output of numpy.extract() function is the same elements that we want to filter, whereas in numpy.where() function, the output is an array containing only those elements that satisfy the given condition.
<br>

- ### The numpy.extract() function is widely used in various data analysis tasks such as data filtering, data cleaning, and data manipulation, because it allows us to easily filter the elements of any array.
<br>

# Parameter
<br>

- ## condition Required
- ## arr Required


In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.extract(condition=arr&2==0, arr=arr)

array([1, 4, 5, 8, 9])

# *np.compress()*
<br>

- ### The "np.compress()" function in NumPy is used for data filtering. This function is used to extract specific parts of data. With this function, we can obtain only those parts of the data that we want.
<br>

- ### Syntax: np.compress(condition, arr, axis=None)
<br>

- ### Here, the 'condition' parameter is a boolean array, which helps us identify the specific parts of the data. The 'arr' parameter is the input array from which we want to extract the data. The 'axis' parameter is optional, which helps us specify the axis on which to apply the compress operation.
<br>

- ### By using this function, we can filter specific parts of the data. If the condition array is True, the corresponding value is extracted, and if it is False, the value is ignored. This way, we only get the values that we need.
<br>

- ### Before using this function, we need to set the condition array correctly. Setting the right values in the condition array allows us to filter specific parts of the data.
<br>

- ### This function can be used to filter any data where we want to extract specific parts.

In [9]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [10]:
condition = np.array([False, True, False, True, False])

In [11]:
np.compress(condition, arr,axis=0)

array([2, 4])

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# axis parameters
np.compress([False, True, False], arr, axis=1)

array([[2],
       [5],
       [8]])

In [14]:
arr = np.array([1, 2, 3, 4, 5],np.int32)
arr

array([1, 2, 3, 4, 5], dtype=int32)

In [15]:
out_arr = np.empty(3,np.int32) # temp array
out_arr

array([-1647657219,       21906,           0], dtype=int32)

- ### The out parameter in the np.compress() function is an optional parameter that allows us to specify the output array where the result of the compression will be stored.
<br>

- ### If the out parameter is not provided, the function will create a new array to store the compressed data. However, if we pass an array as the out parameter, the function will use that array to store the compressed data instead of creating a new array.
<br>

- ### This can be useful in situations where we have an existing array that we want to use to store the compressed data, rather than creating a new array. It can help to save memory and improve performance.

In [16]:
condition = np.array([True, False, True, False, True])

In [17]:
np.compress(condition, arr, out=out_arr)
# according to condition output is 1 3 5 and that also store in out_arr array

array([1, 3, 5], dtype=int32)

In [18]:
out_arr

array([1, 3, 5], dtype=int32)

# *np.take()*
<br>

- ### In NumPy, the take() function is used to select elements from an array based on their index numbers. The syntax of this function is numpy.take(arr, indices, axis=None, out=None, mode='raise'), where arr is the input array, indices is a list of index numbers of the selected elements, and axis and out are optional arguments.
<br>

- ### By using this function, we can select the corresponding elements at the specified index numbers in the array. If the same index number is repeated in the indices list, the corresponding element will also be repeated.
<br>

- ### The take() function can be used to select elements corresponding to any axis. If the axis argument is not given, the function will select the corresponding elements of the flat array.
<br>

- ### Similarly, by using the out argument, we can store the selected elements in another array. The mode argument is used for error handling.
<br>

# Parameter
<br>

- ## a Required
- ## indices Required
- ## axis optional
- ## out optional
- ## mode optional

In [19]:
arr

array([1, 2, 3, 4, 5], dtype=int32)

In [20]:
indices = [0,2,4]
np.take(a=arr,indices=indices)

array([1, 3, 5], dtype=int32)

In [21]:
# use out parameter
temp = np.empty(3,np.int32)
temp

array([-1647657326,       21906,           0], dtype=int32)

In [22]:
np.take(a=arr,indices=indices,out=temp) # 1 3 5 also store in temp

array([1, 3, 5], dtype=int32)

In [23]:
temp

array([1, 3, 5], dtype=int32)

In [24]:
# use axis parameter
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
indices = [0,2] 
np.take(a=arr,indices=indices,axis=0) # axis 0 for select only 0 and 2 rows

array([[1, 2, 3],
       [7, 8, 9]])

- ### The main difference between np.compress() and np.extract() is in their output.
<br>

- ### np.compress() returns a flattened array containing only the elements that correspond to True values in the condition array.
<br>

- ### On the other hand, np.extract() returns a 1D array containing only the elements that satisfy the condition, without flattening the array.
<br>

- ### In other words, np.compress() returns a subset of the input array that passes a certain condition, while np.extract() returns the elements themselves that pass the condition.
<br>

- ### Another difference is that np.compress() takes an optional axis parameter to apply the condition along a certain axis, while np.extract() does not have this option

In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
# use take function
indices = [0, 2]
result = np.take(arr, indices,axis=0)
result

array([[1, 2, 3],
       [7, 8, 9]])

In [28]:
# use compress function
condition = [True, False, True]
result = np.compress(condition, arr,axis=0)
result

array([[1, 2, 3],
       [7, 8, 9]])

# *np.put()*
<br>
    
- ### In NumPy, the put() function is used to set the value of elements in an array. The syntax of this function is numpy.put(arr, ind, v, mode='raise'), where arr is the input array, ind is a list containing the index numbers of the elements we want to change, v is a list containing the updated values, and mode is an optional argument.
<br>

- ### Using this function, we can set the value of elements in the array corresponding to the specified index numbers. If the same index number is repeated in ind, the value of the corresponding element is also repeated.
<br>

- ### By using the put() function, we can set the value of elements corresponding to any axis of the array. If the axis argument is not provided, the value of elements corresponding to the flat array is set.
<br>

- ### Similarly, the mode argument is used for error handling. If mode='raise', a ValueError is raised for out-of-bounds index elements. If mode='wrap', the indices are wrapped according to the length of the array.
<br>

- ### The put() function is used in array manipulation where we want to change the value of elements corresponding to specific index numbers.
<br>

# Parameters
<br>

- ## arr Required
- ## ind Required
- ## v Required
- ## mode Optional

In [29]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [30]:
idx = [0, 2, 4]
vals = [-1, -2, -3]

In [31]:
np.put(arr, idx, vals, mode='clip')

In [32]:
arr

array([-1,  2, -2,  4, -3,  6])

In [33]:
idx = [0, 2, 6] # outof range
np.put(arr, idx, vals, mode='clip') # dont raise the error clip
arr

array([-1,  2, -2,  4, -3, -3])

In [34]:
np.put(arr, idx, vals, mode='raise') # now use raise

IndexError: index 6 is out of bounds for axis 0 with size 6

In [35]:
np.put(arr, idx, vals, mode='wrap') # mode wrap

In [36]:
arr

array([-3,  2, -2,  4, -3, -3])

# *np.clip()*

<br>

- ### The np.clip() function is used in numpy to limit the values of each element in a numpy array to be within a specified minimum and maximum range. 
<br>

- ### If an element is smaller than the minimum limit, its value is set to the minimum limit, and if an element is larger than the maximum limit, its value is set to the maximum limit.
<br>

- ### By using this function, we can clip values outside a specified range to the minimum and maximum limits, and map such values to the minimum and maximum limits. 
<br>

- ### This can be useful when visualizing data or training an algorithm where we need to normalize the minimum and maximum values of data within a specified range.
<br>

# Parameters
<br>

- ## a Required
- ## a_min Required
- ## a_max Required

In [49]:
arr = np.array([-5, 0, 10, 15, 20])
arr

array([-5,  0, 10, 15, 20])

In [50]:
np.clip(a=arr, a_min=0, a_max=10)

array([ 0,  0, 10, 10, 10])

# *np.putmask()*
<br>

- ### In NumPy, the putmask() function is used to set the values of elements in an array based on a specified condition. The syntax of this function is numpy.putmask(arr, mask, values), where arr is the input array, mask is a boolean array that defines the condition, and values is a list of updated values.
<br>

- ### By using this function, we can set the values of elements in an array based on a specified condition. If any element in the mask array has a value of True, the corresponding element in the arr array is updated with the corresponding value in the values list.
<br>

- ### The putmask() function can be used to set the values of elements in an array for any axis. If the axis argument is not specified, then the corresponding elements in the flat array are set.
<br>

- ### The putmask() function is commonly used in array manipulation when we want to change the values of specific elements based on a specific condition.
<br>

# Parameters
<br>

- ## a Required
- ## mask Required
- ## values Required

In [39]:
arr = np.array([-1, 2, -3, 4, -5])
arr

array([-1,  2, -3,  4, -5])

In [40]:
mask = arr < 0
mask

array([ True, False,  True, False,  True])

In [41]:
values = 0

In [42]:
np.putmask(arr, mask=mask, values=values)

In [43]:
arr

array([0, 2, 0, 4, 0])

# *np.unique()*
<br>

- ### In NumPy, the unique() function is used to find unique values in an array. The syntax of this function is numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None), where ar is the input array and return_index, return_inverse, return_counts, and axis are optional arguments.
<br>

- ### By using the unique() function, we can find the unique values in an array. If the return_index argument is True, then an array of index positions corresponding to unique values is returned. If the return_inverse argument is True, then an array of the inverse index positions corresponding to unique values is returned. If the return_counts argument is True, then an array of the occurrence count of unique values is returned.
<br>

- ### The unique() function is used to find unique values corresponding to the flat list of an array. Similarly, if the axis argument is 0, then unique values corresponding to the rows are found, and if the axis argument is 1, then unique values corresponding to the columns are found.

In [44]:
arr = np.array([1, 2, 1, 2, 2, 1, 5, 6, 5])
arr

array([1, 2, 1, 2, 2, 1, 5, 6, 5])

In [45]:
unique_values = np.unique(arr)
unique_values

array([1, 2, 5, 6])

# *np.nonzero()*
<br>

- ### The numpy.nonzero() function is a function available in the NumPy library of Python, which helps us to find the indices or locations of non-zero elements in an array.
<br>

- ### If we want to find the indices or locations of non-zero elements in an array, we can use the numpy.nonzero() function. With this function, we can return a tuple that contains the indices or locations of non-zero elements in an array.
<br>

- ### In the numpy.nonzero() function, we pass only one argument which is the array for which we want to find the indices of non-zero elements.
<br>

- ### The output of this function is a tuple that contains arrays. Each array contains the indices of non-zero elements in one dimension of the input array.
<br>

- ### The numpy.nonzero() function is widely used in various data analysis tasks such as data filtering, data cleaning, and data manipulation because it allows us to easily extract the indices or locations of non-zero elements in an array.

In [46]:
arr = np.array([0, 2, 0, 0, 5, 9, 0, 7, 0])
arr

array([0, 2, 0, 0, 5, 9, 0, 7, 0])

In [47]:
positions = np.nonzero(arr)
positions

(array([1, 4, 5, 7]),)

In [48]:
# now we use the positions to pass inside indexing for access only nonzeros elements
arr[positions]

array([2, 5, 9, 7])