# Logical Functions

- ## *np.all()*
- ## *np.any()*
- ## *np.greater()*
- ## *np.greater_equal()*
- ## *np.less()*
- ## *np.less_equal()*
- ## *np.equal()*
- ## *np.not_equal()*
- ## *np.logical_end()*
- ## *np.logical_or()*
- ## *np.logical_not()*
- ## *np.logical_xor()*

# Checking Functions

- ## *np.isin()*
- ## *np.isinf()*
- ## *np.nan()*
- ##  *np.isfinite()*
- ## *np.isscalar()*


In [1]:
import numpy as np

# *np.all()*
<br>

- ### The numpy.all() function is used to check if all elements along a specified axis of a numpy array evaluate to True. It returns True if all elements are True, otherwise it returns False.

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
np.all(arr > 0)

True

In [5]:
# axis
np.all(arr > 0,axis=0)

array([ True,  True,  True])

In [6]:
np.all(arr > 0,axis=1)

array([ True,  True])

# *np.any()*
<br>

- ### The numpy.any() function is used to check if any elements along a specified axis of a numpy array evaluate to True. It returns True if at least one element is True, otherwise it returns False.

In [7]:
print(np.any(arr > 5))

True


In [8]:
np.any(arr > 5,axis=0) # axis

array([False, False,  True])

In [9]:
np.any(arr > 5,axis=1)

array([False,  True])

# *np.greater()*
<br>

- ### np.greater() is to compare each element of two arrays with their corresponding elements and return True if the element in the first array is greater than the corresponding element in the second array, and False if it is less than or equal to it.
<br>

- ### We use this function when we need to extract data points that satisfy a particular range or condition from any data set.

In [2]:
a = np.array([2, 5, 7, 9, 3])
b = np.array([3, 4, 6, 8, 2])

In [3]:
np.greater(a,b) # a > b

array([False,  True,  True,  True,  True])

In [4]:
a > b

array([False,  True,  True,  True,  True])

# *np.greater_equal()*
<br>

- ### np.greater_equal is a comparison operator used in programming languages to compare two values or variables. It is denoted by ">=" symbol and returns true if the first value is greater than or equal to the second value.

In [5]:
np.greater_equal(a,b)

array([False,  True,  True,  True,  True])

In [6]:
a >= b

array([False,  True,  True,  True,  True])

# *np.less()*
<br>

- ### The np.less() function is a NumPy library function that compares two arrays element-wise and returns a boolean array where the elements are True where the corresponding elements of the first array are less than the second array's elements and False where they are not.

In [7]:
np.less(a,b)

array([ True, False, False, False, False])

In [8]:
a < b

array([ True, False, False, False, False])

# *np.less_equal()*
<br>

- ### np.less_equal() is a function provided by the NumPy library in Python, and it is used to compare two arrays element-wise to determine if the elements in the first array are less than or equal to the corresponding elements in the second array.

In [9]:
np.less_equal(a,b)

array([ True, False, False, False, False])

In [10]:
a <= b

array([ True, False, False, False, False])

# *np.equal()*
<br>

- ### np.equal() is a function provided by the NumPy library in Python, and it is used to compare two arrays element-wise to determine if the elements in the first array are equal to the corresponding elements in the second array.

In [11]:
a = np.array([2, 5, 7, 9, 3])
b = np.array([3, 5, 7, 8, 2])

In [12]:
np.equal(a,b)

array([False,  True,  True, False, False])

In [13]:
a == b

array([False,  True,  True, False, False])

# *np.not_equal()*
<br>

- ### np.not_equal() is a function provided by the NumPy library in Python, and it is used to compare two arrays element-wise to determine if the elements in the first array are not equal to the corresponding elements in the second array.

In [14]:
np.not_equal(a,b)

array([ True, False, False,  True,  True])

In [15]:
a != b

array([ True, False, False,  True,  True])

# *np.logical_and()*
<br>

- ### np.logical_and() is a function provided by the NumPy library in Python, and it is used to compute the element-wise logical AND of two boolean arrays.

In [16]:
np.logical_and(a,b)

array([ True,  True,  True,  True,  True])

# *np.logical_or*
<br>

- ### np.logical_or() is a function provided by the NumPy library in Python, and it is used to compute the element-wise logical OR of two boolean arrays.

In [17]:
np.logical_or(a,b)

array([ True,  True,  True,  True,  True])

# *np.logical_xor()*
<br>

- ### np.logical_xor() is a function provided by the NumPy library in Python, and it is used to compute the element-wise logical XOR (exclusive OR) of two boolean arrays.

In [18]:
np.logical_xor(a,b)

array([False, False, False, False, False])

# *np.logical_not()*
<br>

- ### np.logical_not() is a function provided by the NumPy library in Python, and it is used to compute the element-wise logical NOT of a boolean array.

In [19]:
print(a)
print()
print(b)

[2 5 7 9 3]

[3 5 7 8 2]


In [20]:
np.logical_not(a,b) # also change the value b

array([0, 0, 0, 0, 0])

In [21]:
a

array([2, 5, 7, 9, 3])

In [22]:
b

array([0, 0, 0, 0, 0])

# Checking Function

# *np.isin()*
<br>

- ### np.isin() is a NumPy function that is used in Python, and it returns a boolean array. This function is used to match elements in any array with each other.

In [23]:
a = np.array([2, 3, 5, 7, 11, 13])
a

array([ 2,  3,  5,  7, 11, 13])

In [24]:
b = np.array([2, 3, 5,])
b

array([2, 3, 5])

In [25]:
np.isin(a,b)

array([ True,  True,  True, False, False, False])

# *np.isinf()*
<br>

- ### np.isinf() is a function provided by the NumPy library in Python, and it is used to check whether each element of an array is positive or negative infinity.

In [26]:
arr = np.array([1,2,3,np.inf])
arr

array([ 1.,  2.,  3., inf])

In [27]:
np.isnan

<ufunc 'isnan'>

# *np.nan()*
<br>

- ### np.nan is a special floating-point value that represents "Not a Number". It is a value that is often used to indicate missing or undefined data in a dataset.
<br>

- ### In NumPy, np.nan can be used in arrays and computations in the same way as other numeric values. However, any arithmetic operation involving np.nan will result in np.nan

In [28]:
arr = np.array([1, 2, np.nan, 4, np.nan])
arr

array([ 1.,  2., nan,  4., nan])

In [29]:
np.isnan(arr)

array([False, False,  True, False,  True])

# *np.isfinite()*
<br>

- ### The np.isfinite() function is a NumPy library function that checks whether the elements of a given array are finite (i.e., not NaN or infinity) or not. It returns a boolean array where the elements are True where the corresponding elements of the input array are finite and False where they are not.

In [31]:
arr = np.array([1, 2, np.nan, 4, np.inf, -np.inf, 7])
arr

array([  1.,   2.,  nan,   4.,  inf, -inf,   7.])

In [32]:
np.isfinite(arr)

array([ True,  True, False,  True, False, False,  True])

# *np.isscalar()*
<br>

- ### The np.isscalar() function is a NumPy library function that checks whether a given object is a scalar or not. It returns a boolean value True if the object is a scalar and False if it is not.

In [33]:
np.isscalar(10)

True

In [34]:
np.isscalar([1,2,3])

False

In [35]:
np.isscalar(np.array([1,2,3]))

False