- ## *np.add()*
- ## *np.subtract()*
- ## *np.multiply()*
- ## *np.divide()*
- ## *np.floor_divide()*
- ## *np.mod()*
- ## *np.modf()*
- ## *np.power()*
- ## *np.square()*
- ## *np.sqrt()*
- ## *np.exp()*
- ## *np.abs()*
- ## *np.fabs()*
- ## *np.sign()*
- ## *np.ceil()*
- ## *np.floor()*
- ## *np.rint()*
- ## *np.round()*

# *np.add*
<br>

- ### np.add is a function in the NumPy library of Python that is used to add two arrays. This function adds the corresponding elements of both arrays and returns a new array that is formed by element-wise sum of the two arrays.

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a,"\n")
print(b,"\n")

[1 2 3] 

[4 5 6] 



In [3]:
np.add(a,b) # same like as  a+b

array([5, 7, 9])

In [4]:
a + b

array([5, 7, 9])

# *np.sum()*

# *np.subtract()*
<br>

- ### np.subtract is a function in the NumPy library of Python that is used to find the difference (or subtraction) between two arrays. This function subtracts the corresponding elements of both arrays and returns a new array that is formed by element-wise difference of the two arrays.

In [5]:
print(a,"\n")
print(b,"\n")

[1 2 3] 

[4 5 6] 



In [6]:
np.subtract(a,b)

array([-3, -3, -3])

In [7]:
np.subtract(b,a)

array([3, 3, 3])

# *np.multiply*
<br>
    
- ### np.multiply is a function in the NumPy library of Python that is used to multiply two arrays. This function multiplies the corresponding elements of both arrays and returns a new array that is formed by element-wise product of the two arrays."

In [8]:
print(a,"\n")
print(b,"\n")

[1 2 3] 

[4 5 6] 



In [9]:
np.multiply(a,b)

array([ 4, 10, 18])

# *np.divide()*
<br>

- ### np.divide is a function in the NumPy library of Python that is used to divide two arrays. This function divides the corresponding elements of both arrays and returns a new array that is formed by element-wise division of the two arrays

In [10]:
np.divide(a,b)

array([0.25, 0.4 , 0.5 ])

# *np.floor_divide()*
<br>

- ### np.floor_divide is a NumPy library function that performs floor division between two arrays. Floor division is an operation in which the result of the division is rounded down to the nearest integer, meaning that the digits after the decimal point are discarded.

In [11]:
np.floor_divide(a,b)

array([0, 0, 0])

In [12]:
np.floor_divide(b,a)

array([4, 2, 2])

# *np.power()*
<br>

- ### np.power is a function in the NumPy library of Python, which raises all the elements of a given array to the power of a specified exponent. The function takes two arguments, where the first argument is the base and the second argument is the exponent. It returns a new array where each element of the original array has been raised to the power of the specified exponent.

In [13]:
np.power(a,1)

array([1, 2, 3])

In [14]:
np.power(a,2)

array([1, 4, 9])

In [15]:
np.power(a,b)

array([  1,  32, 729])

# *np.square()*
<br>

- ### np.square is a NumPy library function that computes the square (i.e., raises to the power of 2) of all the elements in a given array. This function is commonly used in numerical calculations where we need to calculate the square of a variable. It returns a new array in which all the elements of the original array have been squared.

In [16]:
np.square(a)

array([1, 4, 9])

# *np.sqrt()*
<br>

- ### "np.sqrt" is a Python NumPy library function used to calculate the square root (i.e., raised to the power of 1/2) of all the elements in an array. This function is generally used in numerical calculations where we need to calculate the square root of a variable. 
<br>

- ### It returns a new array where all the elements of the original array are the square roots of their corresponding elements.
<br>

- ### Only float dtype required

In [17]:
np.sqrt(np.float32(a)) # first convert into float

array([1.       , 1.4142135, 1.7320508], dtype=float32)

# *np.mod()*
<br>

- ### np.mod is a Python NumPy library function that is used to calculate element-wise modulus (or remainder) between two arrays. The first argument in the function is the dividend and the second argument is the divisor.
<br>

- ### The function calculates the remainder or modulus by dividing the corresponding elements of both arrays. The function returns a new array which contains the remainders of the corresponding elements of the given arrays. This function is commonly used for mathematical calculations in various applications.

In [18]:
np.mod(a,b)

array([1, 2, 3])

# *np.modf()*
<br>

- ### "modf" is a NumPy library function that separates a given number into its integer part (whole number) and fractional part (decimal). This means that if we want to store the integer and fractional parts of a number in separate variables, we can use the "modf" function.
<br>

- ### This function is generally used in numerical calculations where we need to use the integer part and fractional part of a number separately. The function returns a tuple, with the first element being the fractional part and the second element being the integer part.

In [19]:
x = 3.14159
x

3.14159

In [20]:
fractional, integral = np.modf(x)

In [21]:
fractional

0.14158999999999988

In [22]:
integral

3.0

In [23]:
a

array([1, 2, 3])

# *np.exp()*
<br>

- ### np.exp is a Python NumPy library function that is used to calculate the exponential (i.e., e raised to the power) of all elements of an array. This function is generally used in mathematical calculations where we need to calculate the exponential of a variable. The function returns a new array in which all elements of the original array have been exponentiated.
<br>

- ## Only float dtype required

In [24]:
a

array([1, 2, 3])

In [25]:
np.exp(np.float32(a))

array([ 2.718282 ,  7.3890557, 20.085537 ], dtype=float32)

# *np.abs()*
<br>

- ### "np.abs" is a NumPy library function that is used to calculate the absolute value (i.e., the magnitude or distance from zero) of all elements in an array. This function is generally used in numerical calculations where we need to determine the magnitude of a variable. The function returns a new array in which all elements of the original array are their absolute value.

In [26]:
np.abs([1,2,-10,-30])

array([ 1,  2, 10, 30])

# *np.fabs()*
<br>

- ### "np.fabs" is also a NumPy library function like "np.abs" that is used to calculate the absolute value of all elements in an array. This means that the function calculates the magnitude or distance from zero of all elements in the array. The only difference between "np.fabs" and "np.abs" is that "np.fabs" can only be used for float data type, while "np.abs" can be used for any data type.

In [27]:
np.fabs([1,2,-10,-30])

array([ 1.,  2., 10., 30.])

# *np.sign()*
<br>

- ### np.sign is a NumPy library function that is used to calculate the sign (positive, negative, or zero) of all elements in an array. This function is generally used in numerical calculations where we need to determine the sign of a variable. The function returns a new array containing the sign (+1, -1, or 0) of each element in the original array.

In [28]:
arr = np.array([-3, 0, 2.5, -7, 9])
arr

array([-3. ,  0. ,  2.5, -7. ,  9. ])

In [29]:
np.sign(arr)

array([-1.,  0.,  1., -1.,  1.])

# *np.ceil()*
<br>

- ### np.ceil is a NumPy library function used to replace any number with its next integer that is greater than the number. Its use is generally in numerical calculations where we need to replace a variable with its next integer value. The function returns a new integer value.

In [30]:
arr

array([-3. ,  0. ,  2.5, -7. ,  9. ])

In [31]:
np.ceil(arr)

array([-3.,  0.,  3., -7.,  9.])

# *np.floor()*
<br>

- ### "np.floor" is a NumPy library function that is used to replace any number with its previous integer, which is smaller than that number. Its use is generally seen in numerical calculations where we need to replace a variable with its previous integer value. The function returns a new integer value.
<br>

- ### This function can be used to convert any number into a lower integer value. For example, if we need to remove the decimal places of a number, we can use the np.floor function.

In [32]:
arr = np.array([2.5, 3.8, 1.2, 4.9, 6.7])
arr

array([2.5, 3.8, 1.2, 4.9, 6.7])

# *np.rint()*
<br>

- ### "np.rint" is a NumPy library function that is used to round any number to its nearest integer value. This function is generally used in numerical calculations where we need to replace a variable with its nearest integer value. The function returns a new integer value.
<br>

- ### This function can be used to round any number. For example, if we need to round a number to the nearest value of 0.5, we can use the np.rint function.

In [33]:
arr

array([2.5, 3.8, 1.2, 4.9, 6.7])

In [34]:
np.rint(arr)

array([2., 4., 1., 5., 7.])

## *np.round()*
<br>

- ### np.round is a NumPy library function that is used to round off any number to its nearest integer value. This function is generally used in numerical calculations where we need to replace a variable with its nearest integer value. The function returns a new integer value.
<br>

# Parameters
<br>

- ## a
- ## decimal Optional


In [35]:
np.round(a=arr)

array([2., 4., 1., 5., 7.])

In [36]:
np.round(a=arr,decimals=0)

array([2., 4., 1., 5., 7.])

In [37]:
np.round(a=arr,decimals=1) # change decimals

array([2.5, 3.8, 1.2, 4.9, 6.7])