# Numpy's numerical ranges functions are used to analyze and manipulate data in arrays. These functions are very useful for scientific computing.

- ## *np.arange()*
- ## *np.linespace()*
- ## *np.logspace()*
- ## *np.geomspace()*
- ## *np.meshgrid()*
- ## *np.mgrid()*
- ## *np.ogrid()*

# *np.arange()*
<br>

- ### The numpy arange() function is used to generate a numpy array (sequence). Through this function, we can specify the range of the array elements, the step size between consecutive elements, and whether the range is inclusive or exclusive.
<br>

- ### This function typically has three arguments: start, stop, and step. We use the start argument to specify the first element of the array, the stop argument to specify the last element of the array, and the step argument to specify the difference between consecutive elements.
<br>

- ### For example, if we use arange(0, 10, 2), it will generate the [0, 2, 4, 6, 8] array where the start value is 0, the stop value is 10 (exclusive), and the step size is 2.
<br>

# Parameters
<br>

- ## start Optional
- ## end Required
- ## skip Optional
- ## dtype Optional

In [1]:
import numpy as np

In [2]:
np.arange(3)

array([0, 1, 2])

In [3]:
# start 1 ,
# end 4 (n-1)
np.arange(1,4)

array([1, 2, 3])

In [4]:
# skip argument
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [5]:
# also use reverse parameters
np.arange(-3,4)

array([-3, -2, -1,  0,  1,  2,  3])

# *np.linespace()*
<br>

- ### The np.linspace() function of numpy is used to generate elements of a numpy array. This function generates a specific number of evenly spaced elements between the start value and the stop value of the array.
<br>

- ### The linspace() function is also used for creating graphs and plots where we need evenly spaced values for the x-axis. Apart from this, there are many other numerical range functions in numpy that are used for analyzing and manipulating data in arrays.
<br>

# Parameters
<br>

- ## start
- ## stop
- ## num
- ## endpoint
- ## retstep
- ## dtype

In [6]:
start = 1
end = 6
num = 6
np.linspace(start,end,num)

array([1., 2., 3., 4., 5., 6.])

In [7]:
start = 1
end = 6
num = 3
np.linspace(start,end,num)

array([1. , 3.5, 6. ])

In [8]:
start = 1
end = 6
num = 10
np.linspace(start,end,num,retstep=False)

array([1.        , 1.55555556, 2.11111111, 2.66666667, 3.22222222,
       3.77777778, 4.33333333, 4.88888889, 5.44444444, 6.        ])

In [9]:
np.linspace(start,end,num,retstep=True)

(array([1.        , 1.55555556, 2.11111111, 2.66666667, 3.22222222,
        3.77777778, 4.33333333, 4.88888889, 5.44444444, 6.        ]),
 0.5555555555555556)

In [10]:
np.linspace(start,end,num,retstep=True,endpoint=False)

(array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5]), 0.5)

In [11]:
np.linspace(start,end,num,retstep=True,endpoint=False,dtype=int)

(array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5]), 0.5)

# *np.logspace()*
<br>

- ### The numpy.logspace() function in NumPy helps us generate numbers on a logarithmic scale, i.e., logarithmically spaced numbers.
<br>

- ### The numbers generated by the logspace() function are evenly spaced on a logarithmic scale, which is quite useful for scientific and engineering calculations.
<br>

- ### This function is very useful in data analysis where we need to analyze data on a logarithmic scale.
<br>

# Parameters
<br>

- ## start
- ## stop
- ## num
- ## endpoint
- ## base
- ## dtype
- ## axis

In [16]:
start = 1
stop = 12
np.logspace(start=start,stop=stop,num=3)

array([1.00000000e+01, 3.16227766e+06, 1.00000000e+12])

In [26]:
start = 1
stop = 6
np.logspace(start=start,stop=stop,num=6)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06])

In [27]:
start = 1
stop = 6
np.logspace(start=start,stop=stop,num=6,dtype=int)

array([     10,     100,    1000,   10000,  100000, 1000000])

In [30]:
np.logspace(start=start,stop=stop,num=6,dtype=float,endpoint=False)

array([1.00000000e+01, 6.81292069e+01, 4.64158883e+02, 3.16227766e+03,
       2.15443469e+04, 1.46779927e+05])

In [36]:
np.logspace(start=start,stop=stop,num=6,dtype=float,endpoint=False,base=2)

array([ 2.        ,  3.56359487,  6.34960421, 11.3137085 , 20.1587368 ,
       35.91878555])

# *np.geomspace()*
<br>

- ### The geomspace() function in NumPy helps us generate geometrically spaced numbers. With this function, we can generate numbers in a geometric progression.
<br>

- ### The numbers generated by the geomspace() function are evenly spaced in a geometric progression. This means that the numbers are generated by multiplying a fixed multiplier.
<br>

- ### This function is useful in scientific and engineering calculations where data analysis needs to be performed in a geometric progression.
<br>

# Parameters
<br>

- ## start
- ## stop
- ## num
- ## endpoint
- ## dtype
- ## axis

In [39]:
start = 1
stop = 12
np.geomspace(start=start,stop=stop,num=3)

array([ 1.        ,  3.46410162, 12.        ])

In [40]:
start = 1
stop = 6
np.geomspace(start=start,stop=stop,num=6)

array([1.        , 1.43096908, 2.04767251, 2.93015605, 4.19296271,
       6.        ])

In [41]:
start = 1
stop = 6
np.geomspace(start=start,stop=stop,num=6,dtype=int)

array([1, 1, 2, 2, 4, 6])

In [42]:
np.geomspace(start=start,stop=stop,num=6,dtype=float,endpoint=False)

array([1.        , 1.34800615, 1.81712059, 2.44948974, 3.30192725,
       4.45101825])

# np.meshgrid()
<br>

- ### The NumPy meshgrid() function helps us generate a mesh grid. A mesh grid means defining a plane or a grid in which our data points are located.
<br>

- ### The meshgrid() function returns a 2D numpy array with coordinates for both axes. It is commonly used in data visualization and plotting.
<br>

# Parameters
<br>

- ## *xi
- ## copy
- ## sparse
- ## indexing

In [44]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7])

In [45]:
x

array([1, 2, 3, 4])

In [46]:
y

array([5, 6, 7])

In [47]:
np.meshgrid(x,y)

[array([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]),
 array([[5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7]])]

In [48]:
xx,yy = np.meshgrid(x,y)

In [49]:
xx

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [50]:
yy

array([[5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]])

In [52]:
np.meshgrid(x,y,sparse=True)

[array([[1, 2, 3, 4]]),
 array([[5],
        [6],
        [7]])]

In [54]:
np.meshgrid(x,y,indexing="xy")

[array([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]),
 array([[5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7]])]

In [55]:
np.meshgrid(x,y,indexing="ij")

[array([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]]),
 array([[5, 6, 7],
        [5, 6, 7],
        [5, 6, 7],
        [5, 6, 7]])]

# *np.mgrid()*
<br>

- ### NumPy has another function called mgrid() that helps us to generate mesh grids. In this function, we have to use slice objects to define the values of the mesh grid's axes.
<br>

- ### Similar to meshgrid() function, the mgrid() function also returns a 2D numpy array containing the coordinates of both axes. However, the major difference is that the mgrid() function returns the coordinates in the form of a numpy array, while the meshgrid() function returns the coordinates in the form of numpy arrays.


In [58]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7])

In [59]:
x

array([1, 2, 3, 4])

In [60]:
y

array([5, 6, 7])

In [63]:
np.meshgrid(x,y)

[array([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]),
 array([[5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7]])]

In [69]:
# use mgrid()
np.mgrid[1:5,5:8]

array([[[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]],

       [[5, 6, 7],
        [5, 6, 7],
        [5, 6, 7],
        [5, 6, 7]]])

# *np.ogrid()*
<br>

- ### In NumPy, ogrid() is a function that helps us to generate a mesh grid. We need to use slice objects to define the axis values in this function.

<br>

- ### The ogrid() function returns a numpy array that contains the coordinates of both axes. The major difference between ogrid() and meshgrid() function is that ogrid() function returns numpy arrays in the form of coordinates, whereas meshgrid() function returns numpy arrays in the form of a 2D grid.
<br>

- ### ogrid() is similar to mgrid(), but it creates a multidimensional "open" grid instead of a "closed" grid. In other words, it returns arrays that have the same shape as the broadcasted arrays but with singleton dimensions expanded to size 1. 
<br>

- ### This can be useful when you need to perform element-wise operations on two arrays with different shapes.

In [70]:
x, y = np.mgrid[0:3, 0:3]

In [71]:
x

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [72]:
y

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [73]:
# using ogrid

x, y = np.ogrid[0:3, 0:3]

In [74]:
x

array([[0],
       [1],
       [2]])

In [75]:
y

array([[0, 1, 2]])