- ## *np.savetxt()*
- ## *np.loadtxt()*
- ## *ndarray.tolist()*
- ## *np.save()*
- ## *np.load()*

# *np.savetxt()*
<br>

- ### The numpy.savetxt() function is used to save a numpy array to a text file. This function takes three main arguments: the file name to save the array to, the array to be saved, and an optional delimiter string that separates the values in the file.

In [1]:
import numpy as np

In [2]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.savetxt("data.txt",data)

In [4]:
cat data.txt

1.000000000000000000e+00 2.000000000000000000e+00 3.000000000000000000e+00
4.000000000000000000e+00 5.000000000000000000e+00 6.000000000000000000e+00
7.000000000000000000e+00 8.000000000000000000e+00 9.000000000000000000e+00


In [5]:
# change delimiter
np.savetxt("data.txt",data,delimiter=";")

In [9]:
cat data.txt

1.000000000000000000e+00;2.000000000000000000e+00;3.000000000000000000e+00
4.000000000000000000e+00;5.000000000000000000e+00;6.000000000000000000e+00
7.000000000000000000e+00;8.000000000000000000e+00;9.000000000000000000e+00


# *np.loadtxt()*
<br>

- ### The numpy.loadtxt() function is used to load data from a text file into a NumPy array. The function reads a text file containing numeric data and returns a NumPy array that can be used for further numerical analysis or manipulation.

In [11]:
np.loadtxt("data.txt",delimiter=";")

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [12]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
# change delimiter 
np.savetxt("data.txt",data,delimiter=",") # save array

In [35]:
np.loadtxt("data.txt",delimiter=",")

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [36]:
# change dtype
np.loadtxt("data.txt",delimiter=",",dtype=int)

/tmp/ipykernel_81663/287599630.py:2: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  np.loadtxt("data.txt",delimiter=",",dtype=int)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
# use astype() function for convert data type 
ds = np.loadtxt("data.txt",delimiter=",")
ds

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [42]:
ds.astype(int)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
# usecols parameter
np.loadtxt("data.txt",delimiter=",",usecols=0)

array([1., 4., 7.])

In [45]:
np.loadtxt("data.txt",delimiter=",",usecols=1)

array([2., 5., 8.])

In [49]:
# skiprows parameter
np.loadtxt("data.txt",delimiter=",",skiprows=1)

array([[4., 5., 6.],
       [7., 8., 9.]])

# *ndarray.tolist()*
<br>

- ### The numpy.ndarray.tolist() function is used to convert a NumPy array to a Python list. This can be useful in cases where you need to pass the array to a function or library that expects a list as input.

In [59]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
data.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# *np.save()*
<br>

- ### The numpy.save() function is used to save a NumPy array to a binary file in NumPy's own ".npy" format. This function is similar to the numpy.ndarray.tofile() function, but it adds some header information to the file that makes it easier to load the array back into memory later.

In [81]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
np.save("data.npy", data)

In [83]:
!cat data.npy

�NUMPYv{'descr': '<i8', 'fortran_order': False, 'shape': (3, 3), }                                                          
	

# *np.load()*
<br>

- ### The numpy.load() function is used to load a binary file that was saved using NumPy's .npy format. This function reads the binary data from the file and returns a NumPy array with the same shape, data type, and values as the original array that was saved.

In [84]:
np.load("data.npy")

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# *np.savez()*
<br>

- ### The numpy.savez() function is used to save multiple NumPy arrays into a single compressed .npz archive file. This function is similar to numpy.save(), but it allows you to save and organize multiple arrays in a single file, which can be more convenient and efficient for large datasets.

In [85]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

In [86]:
np.savez("data.npz", array1=a, array2=b, array3=c) # save arrays

In [87]:
data = np.load("data.npz") # load data
data

In [90]:
# access array
for i in data:
    print(i,data[i])

array1 [1 2 3]
array2 [4 5 6]
array3 [7 8 9]
