- ## *np.random.rand()*
- ## *np.random.randn()*
- ## *np.random.randint()*
- ## *np.random.random_sample()*
- ## *np.random.choice()*
- ## *np.random.permutation()*
- ## *np.random.shuffle()*
- ## *np.random.uniform()*
- ## *np.random.standard_normal()*
- ## *np.random.binomial()*
- ## *np.random.normal()*
- ##  *np.random.beta()*
- ## *np.random.chisquare()*
- ## *np.random.gamma()*
- ## *np.random.seed()*

# *np.random.rand()*
<br>

- ### The numpy.random.rand function is a NumPy function that generates an array of random numbers between 0 and 1 with a uniform distribution. It takes a tuple or integer argument that specifies the shape of the output array.

In [1]:
import numpy as np

In [2]:
np.random.rand(2, 3)

array([[0.55509083, 0.11725422, 0.33782664],
       [0.05828477, 0.23315314, 0.53758077]])

In [3]:
np.random.rand(1, 2)

array([[0.0414362 , 0.87999503]])

In [4]:
np.random.rand(1,10)

array([[0.13137451, 0.30119713, 0.98249314, 0.8255037 , 0.37763702,
        0.85101078, 0.08974434, 0.01029739, 0.21430458, 0.49552536]])

# *np.random.randn()*
<br>

- ### The numpy.random.randn function is a NumPy function that generates an array of random numbers from a standard normal distribution with mean 0 and variance 1. It takes one or more integer arguments that specify the shape of the output array.

In [5]:
np.random.randn(1, 2)

array([[-1.05099741,  0.72349876]])

In [6]:
np.random.rand(1,10)

array([[0.12394433, 0.77437321, 0.13253636, 0.06083959, 0.01778172,
        0.45170382, 0.94070873, 0.83581163, 0.37807419, 0.47333676]])

# *np.random.randint()*
<br>

- ### The numpy.random.randint function is a NumPy function that generates an array of random integers between a specified range. It takes the following arguments:
<br>

- ### low: The lowest (inclusive) integer to be drawn from the distribution.
<br>

- ### high: The highest (exclusive) integer to be drawn from the distribution.
<br>

- ### size: The shape of the output array.

In [7]:
np.random.randint(low=0, high=10, size=5)

array([1, 8, 1, 7, 9])

In [8]:
np.random.randint(low=0, high=10, size=5)

array([3, 7, 1, 6, 7])

In [9]:
np.random.randint(low=0, high=10, size=5)

array([1, 8, 6, 5, 2])

# *np.random.random_sample()*
<br>

- ### The numpy.random.random_sample function is a NumPy function that generates an array of random numbers between 0 and 1 with a uniform distribution. It takes one or more integer arguments that specify the shape of the output array.

In [10]:
np.random.random_sample((2, 3))

array([[0.17360678, 0.83021076, 0.48563864],
       [0.37102622, 0.66158768, 0.90826207]])

In [11]:
np.random.random_sample()

0.45285697240937883

In [12]:
np.random.random_sample(3)

array([0.58815739, 0.93249559, 0.49062771])

In [13]:
np.random.random_sample((1,3))

array([[0.91203881, 0.23114202, 0.82418515]])

# *np.random.choice()*
<br>

- ### The numpy.random.choice function is a NumPy function that randomly chooses elements from a given array. It takes the following arguments:
<br>

- ### a: The input array to choose elements from.
<br>

- ### size: The shape of the output array.
<br>  

- ### replace: Whether to sample with or without replacement. Default is True.
<br>


In [61]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
np.random.choice(array, size=3)

array([7, 7, 2])

In [83]:
np.random.choice(array, size=3,replace=False) # replce False parameter skip duplication

array([7, 0, 1])

In [17]:
np.random.permutation(array)

array([5, 4, 8, 2, 1, 0, 6, 3, 7, 9])

# *np.random.permutation()*
<br>

- ### The np.random.permutation() function in NumPy is used to randomly permute (shuffle) an array or sequence along its first axis. This means that it randomly shuffles the elements of an array along its rows, keeping the columns intact.
<br>

- ### The function takes an array or an integer as an input and returns a new array with the same shape and type as the input array, but with the rows randomly shuffled. If the input is an integer, it returns a shuffled range from 0 to that integer.

In [18]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.random.permutation(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.random.permutation(a)

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

In [21]:
np.random.permutation(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# *np.random.shuffle()*
<br>

- ### The np.random.shuffle() function in NumPy is used to randomly shuffle (permute) the elements of an array in place. This means that it shuffles the elements of an array randomly along its first axis, without creating a new array.
<br>

- ### The function takes an array as an input and shuffles its elements randomly along its first axis. The function operates in-place, which means that it modifies the original array directly.

In [52]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [53]:
np.random.shuffle(a)
print(a)

[1 2 4 3 5]


In [57]:
np.random.shuffle(a)
print(a)

[2 1 5 3 4]


In [60]:
np.random.shuffle(a)
print(a)

[2 4 1 5 3]


# *np.random.uniform()*
<br>

- ### The np.random.uniform() function in NumPy is used to generate random numbers from a uniform distribution. A uniform distribution is a continuous probability distribution where all values within a specified range are equally likely to occur.
<br>

- ### The function takes the following parameters:
<br>

- ### low: the lower bound of the distribution (inclusive)
<br>

- ### high: the upper bound of the distribution (exclusive)
<br>

- ### size: the size of the output array or the shape of the output

In [26]:
np.random.uniform(low=0.0, high=1.0, size=5)

array([0.10189666, 0.07409808, 0.87671222, 0.07071324, 0.36387705])

In [27]:
np.random.uniform(low=0.0, high=1.0, size=3)

array([0.58911899, 0.18412479, 0.43996133])

In [28]:
np.random.uniform(low=1, high=12, size=3)

array([6.86400143, 1.12786236, 4.89348121])

# *np.random.standard_normal()*
<br>

- ### The np.random.standard_normal() function in NumPy is used to generate an array of random numbers that are normally (Gaussian) distributed with a mean of 0 and a standard deviation of 1.

In [29]:
np.random.standard_normal(size=5)

array([ 2.23571971, -0.38049651,  1.29248833, -0.9986806 ,  1.11400228])

In [30]:
np.random.standard_normal(size=3)

array([-0.25846962,  0.71865074,  0.90826664])

In [31]:
np.random.standard_normal(size=3)

array([ 0.87994989, -0.8370385 ,  0.66825734])

# *np.random.binomial()*
<br>

- ### The np.random.binomial() function in NumPy is used to generate an array of random numbers that follow a binomial distribution. A binomial distribution is a discrete probability distribution that represents the number of successes in a fixed number of independent Bernoulli trials (trials that have two possible outcomes: success or failure) with a given probability of success for each trial.
<br>

- ### The function takes the following parameters:
<br>

- ### n: the number of trials
<br>

- ### p: the probability of success for each trial
<br>

- ### size: the size of the output array or the shape of the output



In [32]:
np.random.binomial(n=10, p=0.5, size=3)

array([5, 4, 9])

In [33]:
np.random.binomial(n=10, p=0.5, size=3)

array([5, 4, 4])

In [34]:
np.random.binomial(n=10, p=0.5, size=3)

array([6, 4, 3])

# *np.random.normal()*
<br>

- ### The np.random.normal() function in NumPy is used to generate an array of random numbers that follow a normal (Gaussian) distribution. A normal distribution is a continuous probability distribution that is symmetric around the mean and characterized by its mean (μ) and standard deviation (σ).
<br>

- ### The function takes the following parameters:
<br>

- ### loc (optional): the mean (μ) of the normal distribution (default is 0)
<br>

- ### scale (optional): the standard deviation (σ) of the normal distribution (default is 1)
<br>

- ### size (optional): the size of the output array or the shape of the output (default is None, which returns a single random number)

In [35]:
np.random.normal(loc=0, scale=1, size=3)

array([-1.38335187,  0.1531374 , -0.86569207])

In [36]:
np.random.normal(loc=0, scale=1, size=3)

array([-0.37669732, -0.48938003,  0.92528512])

#  *np.random.beta()*
<br>

- ### The np.random.beta() function in NumPy is used to generate an array of random numbers that follow a beta distribution. The beta distribution is a continuous probability distribution that is defined on the interval [0, 1]. It is a commonly used distribution in statistics, particularly in Bayesian analysis.
<br>

- ### The function takes the following parameters:
<br>

- ### a (required): the shape parameter a > 0
<br>

- ### b (required): the shape parameter b > 0
<br>

- ### size (optional): the size of the output array or the shape of the output (default is None, which returns a single random number)

In [37]:
np.random.beta(a=2, b=5, size=3)

array([0.50995852, 0.11544717, 0.32530564])

In [38]:
np.random.beta(a=2, b=5, size=3)

array([0.08010676, 0.49088323, 0.02543645])

In [39]:
np.random.beta(a=2, b=5, size=3)

array([0.28664388, 0.34499435, 0.77786831])

# *np.random.chisquare()*
<br>

- ### The np.random.chisquare() function in NumPy is used to generate an array of random numbers that follow a chi-square distribution. The chi-square distribution is a continuous probability distribution that arises in statistical inference when analyzing the variance of a normally distributed population.
<br>

- ### The function takes the following parameters:
<br>

- ### df (required): the degrees of freedom parameter
<br>

- ### size (optional): the size of the output array or the shape of the output (default is None, which returns a single random number)

In [40]:
np.random.chisquare(df=2, size=3)

array([0.95105891, 0.01052943, 3.66861748])

In [41]:
np.random.chisquare(df=2, size=3)

array([0.92370514, 7.37931287, 3.48797395])

In [42]:
np.random.chisquare(df=2, size=3)

array([2.01058167, 8.8383355 , 0.20740462])

# *np.random.gamma()*
<br>

- ### The numpy.random.gamma function is used to generate random numbers from the gamma distribution. The gamma distribution is a continuous probability distribution that is commonly used in statistics to model waiting times, shape parameters, and other positive continuous variables.
<br>

- ### The function takes the following parameters:
<br>

- ### shape: (also known as alpha) the shape parameter of the gamma distribution
<br>

- ### scale: (also known as theta) the scale parameter of the gamma distribution
<br>

- ### size: the size of the output array or the shape of the output (default is None, which returns a single random number)

In [43]:
np.random.gamma(shape=2, scale=2, size=3)

array([3.82456803, 1.84445491, 0.66032718])

In [44]:
np.random.gamma(shape=2, scale=2, size=3)

array([5.01517843, 3.31073229, 3.73672492])

In [45]:
np.random.gamma(shape=2, scale=2, size=3)

array([2.44857568, 5.62041473, 3.50096316])

# *np.random.seed()*
<br>

- ### The numpy.random.seed function is used to set the random seed for the NumPy random number generator. The random seed is an integer that is used to initialize the random number generator, which means that setting the random seed to the same value will produce the same sequence of random numbers every time.

In [46]:
np.random.randint(1,10)

8

In [47]:
np.random.randint(1,10)

4

In [48]:
np.random.randint(1,10)

7

In [49]:
np.random.seed(1)
np.random.randint(1,10)

6

In [50]:
a = np.random.rand()
np.random.seed(42)

b = np.random.rand()

np.random.seed(42)

c = np.random.rand()

print("a:", a)
print("b:", b)
print("c:", c)


a: 0.9971848109388686
b: 0.3745401188473625
c: 0.3745401188473625
