# Splitting Functions

- ## *np.hsplit()*
- ## *np.vsplit()*
- ## *np.dsplit()*
- ## *np.array_split()*
- ## *np.split()*

# Joinning Functions

- ## *np.hstack()*
- ## *np.vstack()*
- ## *np.block()*
- ## *np.column_stack()*
- ## *np.dstack()*
- ## *np.stack()*
- ## *np.concatenate()*


# *np.hsplit()*
<br>

- ### In NumPy, the np.hsplit() function is used to split an array into multiple sub-arrays along the horizontal axis. 
<br>

- ### By using the hsplit() function, we can split an array into multiple sub-arrays along the horizontal axis. 
<br>

- ### The value of the indices_or_sections argument defines how many parts the array should be split into. If indices_or_sections is an integer value, then the array will be split into equal parts. 
<br>

- ### If indices_or_sections is a 1D array, then the array will be split at the points defined along the horizontal axis.
<br>

- ### The hsplit() function is used in array manipulation, where we want to split a specific section of the array or divide it into sub-arrays.
<br>

## hsplit() function splits an array horizontally along its 1st axis.
<br>

# Parameters
<br>

- ## ary Required
- ## indices_or_sections Required

In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
arr.shape

(3, 4)

In [4]:
np.hsplit(ary=arr,indices_or_sections=2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [5]:
arr1 , arr2 = np.hsplit(ary=arr,indices_or_sections=2)

In [6]:
print(arr1)
print()
print(arr2)

[[ 1  2]
 [ 5  6]
 [ 9 10]]

[[ 3  4]
 [ 7  8]
 [11 12]]


# *np.vsplit()*
<br>

- ### In NumPy, the vsplit() function is used to split an array into multiple sub-arrays along the vertical axis. When we split an array with the horizontal axis, we use the hsplit() function. But if we want to split an array along the vertical axis, we use the vsplit() function.
<br>

- ### By using the vsplit() function, we can split an array into multiple sub-arrays along the vertical axis. The value of the indices_or_sections argument defines how many parts we want to split the array into. 
<br>

- ### If the indices_or_sections value is an integer, the array will be split into equal parts. If the indices_or_sections value is a 1D array, the array will be split at the points defined along the vertical axis.
<br>

- ### We use the vsplit() function in array manipulation, where we want to split a specific section of the array into sub-arrays.
<br>

## vsplit() function splits an array vertically along its 2nd axis.

<br>

# Parameters
<br>

- ## ary Required
- ## indices_or_sections Required

In [7]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
np.vsplit(ary=arr,indices_or_sections=3) # divide into 3 parts

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [9]:
arr1, arr2, arr3 = np.vsplit(ary=arr,indices_or_sections=3)
print(arr1,"\n")
print(arr2,"\n")
print(arr3)

[[1 2 3 4]] 

[[5 6 7 8]] 

[[ 9 10 11 12]]


# *np.dsplit()*
<br>

- ### In NumPy, the np.dsplit() function is used to split an array into multiple sub-arrays along the depth (3rd axis). While hsplit() function is used to split an array along the horizontal axis and vsplit() function is used to split an array along the vertical axis.
<br>

- ### By using the dsplit() function, we can split an array into multiple sub-arrays along the depth (3rd axis). The value of the indices_or_sections argument defines how many parts we want to split the array into. 
<br>

- ### If indices_or_sections is an integer value, the array is split into equal parts. If it is a 1D array, the array is split at the points defined along the depth (3rd axis).
<br>

- ### The dsplit() function is used in array manipulation where we want to split a specific section of an array or divide it into sub-arrays.

# Parameters
<br>

- ## ary Required
- ## indices_or_sections Required

In [10]:
# need 3d ARRAY
arr = np.arange(12).reshape((1,3, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [11]:
arr.shape # 

(1, 3, 4)

In [12]:
# array have 4 columns do divide by 2
np.dsplit(ary=arr,indices_or_sections=2)

[array([[[0, 1],
         [4, 5],
         [8, 9]]]),
 array([[[ 2,  3],
         [ 6,  7],
         [10, 11]]])]

In [13]:
arr1 , arr2 = np.dsplit(ary=arr,indices_or_sections=2)
print(arr1,"\n")
print(arr2)

[[[0 1]
  [4 5]
  [8 9]]] 

[[[ 2  3]
  [ 6  7]
  [10 11]]]


# *np.array_split()*
<br>

- ### In NumPy, the np.array_split() function is used to split an array into multiple sub-arrays. However, the difference is that no specific axis of the array is specified in this function. When using this function, we are not splitting the array along any particular axis.
<br>

- ### Using the array_split() function, we can split an array into multiple sub-arrays. The value of the indices_or_sections argument determines how many parts the array is split into. 
<br>

- ### If indices_or_sections is an integer value, the array will be split into approximately equal parts. If indices_or_sections is a 1D array, the array will be split at the points specified along the axis of the array.
<br>

- ### When using this function, we are not splitting the array along any particular axis. If we use the hsplit(), vsplit(), or dsplit() functions, we explicitly specify the horizontal, vertical, or depth axis, respectively. However, the axis argument is optional in the array_split() function, and if we do not specify it, the default value of axis=0 is assumed.
<br>

# Parameters
<br>

- ## ary Required
- ## indices_or_sections Required
- ## axis Optional

In [14]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [15]:
np.array_split(ary=arr,indices_or_sections=2,axis=1)

[array([[[0, 1, 2, 3],
         [4, 5, 6, 7]]]),
 array([[[ 8,  9, 10, 11]]])]

In [16]:
arr1,arr2 = np.array_split(ary=arr,indices_or_sections=2,axis=1)

In [17]:
print(arr1,"\n")
print(arr2)

[[[0 1 2 3]
  [4 5 6 7]]] 

[[[ 8  9 10 11]]]


In [18]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.array_split(ary=arr,indices_or_sections=3,axis=0)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [20]:
arr1 , arr2, arr3 = np.array_split(ary=arr,indices_or_sections=3,axis=0)

In [21]:
print(arr1,"\n")
print(arr2,"\n")
print(arr3)

[1 2 3] 

[4 5 6] 

[7 8 9]


# *np.split()*
<br>

- ### In NumPy, the split() function is used to split an array into multiple sub-arrays. In this function, we can explicitly specify which axis we want to use to split the array.
<br>

- ### Using the split() function, we can split an array into multiple sub-arrays. The value of the indices_or_sections argument defines how many parts we want to split the array into. 
<br>

- ### If the indices_or_sections value is an integer, the array will be split into approximately equal parts. If the indices_or_sections value is a 1D array, the array will be split at the points defined on the specified axis.
<br>

- ### In this function, we can explicitly specify which axis we want to use to split the array. If we use the hsplit(), vsplit(), or dsplit() functions, we explicitly specify the horizontal, vertical, or depth axis. However, in the split() function, the axis argument is optional, and if we do not specify it, the default value of axis=0 will be assumed.
<br>


# Parameters
<br>

- ## ary Required
- ## indices_or_sections Required
- ## axis Optional

In [22]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
np.split(ary=arr,indices_or_sections=2) # default axis is 0
# axis 0 means split vertical wise

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [24]:
np.split(ary=arr,indices_or_sections=2,axis=0) # use axis 0

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [25]:
np.split(ary=arr,indices_or_sections=2,axis=1) # use axis 1 dor split horinzontal wise

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

# *np.hstack()*
<br>

- ### In NumPy, the hstack() function is used to concatenate two or more arrays along the horizontal axis. It is important to note that before using this function, the number of rows in the arrays should be the same, but the number of columns can be different.
<br>

- ### The syntax for hstack() function is numpy.hstack(tup), where tup is a tuple of ndarrays.
<br>

- ### By using hstack() function, we can concatenate two or more arrays along the horizontal axis. However, before concatenating the arrays, the number of rows in them should be the same, but the number of columns can be different. 
<br>

- ### After concatenating the arrays, the output array will have the same dimensions as the input arrays.
<br>

- ### To use this function, we first pass the arrays that we want to concatenate in the tuple argument, and then use the hstack() function to concatenate these arrays along the horizontal axis.

In [26]:
arr1 = np.arange(1,4).reshape(1,3)
arr2 = np.arange(4,7).reshape(1,3)

print(arr1)
print(arr1)

[[1 2 3]]
[[1 2 3]]


In [27]:
np.hstack((arr1,arr2)) # ? why horizontal stack not work ?
# this arrays are verticle form

array([[1, 2, 3, 4, 5, 6]])

## Again read this line 
<br>

- ### It is important to note that before using this function, the number of rows in the arrays should be the same, but the number of columns can be different.

In [28]:
# so change the column of 1 array

arr1 = np.arange(1,4).reshape(3,1)
arr2 = np.arange(4,7).reshape(3,1)

print(arr1)
print(arr2)

[[1]
 [2]
 [3]]
[[4]
 [5]
 [6]]


In [29]:
np.hstack((arr1,arr2)) 

array([[1, 4],
       [2, 5],
       [3, 6]])

In [30]:
np.hstack((arr1,arr2),dtype=float)  # use dtype

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

# *np.vstack()*
<br>

- ### In NumPy, the vstack() function is used to concatenate two or more arrays along the vertical axis. Before using this function, 
<br> 

## we need to make sure that the number of columns in the arrays is the same, *but the number of rows can be different.*

<br>

- ### The syntax for the vstack() function is numpy.vstack(tup), where tup is a tuple of ndarrays.
<br>

- ### By using the vstack() function, we can concatenate two or more arrays along the vertical axis. Before concatenating, we need to make sure that the number of columns in the arrays is the same, but the number of rows can be different. After concatenating, the output array will have the same dimensions as the input arrays.
<br>

- ### To use this function, we first pass the arrays we want to concatenate in the tuple argument tuple and then use the vstack() function to concatenate these arrays along the vertical axis.

In [33]:
arr1

array([[1],
       [2],
       [3]])

In [34]:
arr2

array([[4],
       [5],
       [6]])

In [40]:
arr1 = arr1.T # transpose arr1
arr2 = arr2.T  # transpose arr2

In [41]:
arr1

array([[1, 2, 3]])

In [42]:
arr2

array([[4, 5, 6]])

In [43]:
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6]])

# *np.block()*
<br>

- ### In NumPy, the block() function is used to divide arrays into sub-blocks. This function concatenates multiple arrays in a similar way to hstack() and vstack() functions, but in this function, we divide arrays into sub-blocks before concatenating them.
<br>

- ### The syntax of the block() function is numpy.block(arrays), where arrays is a tuple of ndarrays.
<br>

- ### By using the block() function, we can divide multiple arrays into sub-blocks. We pass multiple arrays in a tuple and then create sub-blocks and concatenate them. In this function, we can also concatenate sub-blocks by slicing them.
<br>

- ### The block() function is different from hstack() and vstack() functions because we can divide multiple arrays into sub-blocks with different shapes. Before using this function, we need to consider the shapes of sub-blocks, while in hstack() and vstack() functions, we only need the numbers of rows or columns to be equal.
<br>

- # np.block() concatenates in verticle wise

In [77]:
# EXAMPLE 1
np.block([[1],[2]])

array([[1],
       [2]])

In [61]:
# EXAMPLE 2
np.block([[1,2],[3,4]]) 

array([[1, 2],
       [3, 4]])

In [65]:
# EXAMPLE 3
np.block([[1,2,3],[4,5,6]]) 

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [71]:
print(arr1)
print()
print(arr2)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [98]:
block1 = [[arr1, arr2], [arr2, arr1]]

In [93]:
np.block(block1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8],
       [5, 6, 1, 2],
       [7, 8, 3, 4]])

# *np.column_stack()*
<br>

- ### In NumPy, the column_stack() function is used to concatenate multiple 1-D or 2-D arrays column-wise. Before using this function, it is important to note that the number of rows in the arrays should be the same, but the number of columns can be different.
<br>

- ### The syntax of the column_stack() function is numpy.column_stack(tup), where tup is a tuple of ndarrays.
<br>

- ### By using the column_stack() function, we can concatenate two or more 1-D or 2-D arrays column-wise. Before concatenating, the number of rows in the arrays should be the same, but the number of columns can be different. After concatenating, the output array will have the same dimensions as the input arrays.
<br>

- ### To use this function, we first pass the arrays that we want to concatenate in a tuple as an argument to tup, and then we use the column_stack() function to concatenate these arrays column-wise.
<br>

- ### The difference between the hstack() and column_stack() functions is that the hstack() function concatenates multiple arrays along the horizontal axis, whereas the column_stack() function converts 1-D arrays into column vectors and then concatenates them. If there are 1-D arrays in the hstack() function, they need to be converted to column vectors before concatenating.

In [94]:
# Example 1
np.column_stack([[1],[2]])

array([[1, 2]])

In [95]:
# EXAMPLE 2
np.column_stack([[1,2],[3,4]]) 

array([[1, 3],
       [2, 4]])

In [96]:
# EXAMPLE 3
np.column_stack([[1,2,3],[4,5,6]]) 

array([[1, 4],
       [2, 5],
       [3, 6]])

In [112]:
np.column_stack([[1,2,3],[3,4,3]]) 

array([[1, 3],
       [2, 4],
       [3, 3]])

# *np.dstack()*
<br>

- ### In NumPy, the dstack() function is used to concatenate multiple arrays along their depth dimension. If we want to concatenate the depth (3rd dimension) of any array, we can use the dstack() function.
<br>

- ### The syntax of the dstack() function is numpy.dstack(tup), where tup is a tuple of multiple ndarrays to be concatenated. The shape of the output array depends on the shapes of the input arrays.
<br>

- ### To use this function, we pass multiple ndarrays in tuples and then concatenate them using the dstack() function. For the output array's shape, it is necessary that the size of all dimensions of input arrays are the same.
<br>

- ### Before using the dstack() function, we need to ensure that the shapes of the input arrays are the same, and the dstack() function is only used to concatenate in the 3rd dimension. If we want to concatenate 2D arrays, we need to use the hstack() function.

In [128]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [129]:
arr1

array([[1, 2],
       [3, 4]])

In [130]:
arr2

array([[5, 6],
       [7, 8]])

In [131]:
np.dstack((arr1, arr2))

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

# *np.stack()*
<br>

- ### In NumPy, the stack() function is used to concatenate multiple arrays into a single dimension. Before using this function, we need to ensure that the size and shape of the arrays are the same.
<br>

- ### The syntax for the stack() function in NumPy is numpy.stack(arrays, axis=0), where arrays are the multiple ndarrays in a tuple that need to be concatenated, and axis defines the dimension to concatenate.
<br>

- ### By using the stack() function, we can concatenate multiple arrays into a single dimension. 
<br>

- ### It is necessary for the size and shape of the arrays to be the same before concatenating. We can define the dimension in which to concatenate the arrays using the axis parameter, which has a default value of 0.
<br>

- ### To use this function, we pass multiple ndarrays in a tuple, and then concatenate them using the stack() function. The shape of the output array depends on the shapes of the input arrays.
<br>

- ### Before using the stack() function, it is important to ensure that the size and shape of the input arrays are the same, along with the dimension to concatenate.

In [116]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [117]:
print(arr1)
print()
print(arr2)

[1 2 3]

[4 5 6]


In [118]:
np.stack((arr1,arr2)) # default axis 0 means column wise

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
np.stack((arr1,arr2),axis=0) # for axis 0

array([[1, 2, 3],
       [4, 5, 6]])

In [120]:
np.stack((arr1,arr2),axis=1) # for axis 1

array([[1, 4],
       [2, 5],
       [3, 6]])

# *np.concatenate()*
<br>

- ### In NumPy, the concatenate() function is used to concatenate multiple arrays. Before using this function, it is important to note that the shapes of input arrays should be the same except for the dimension along which we want to concatenate.
<br>
    
- ### Using the concatenate() function, we can concatenate two or more arrays. Before concatenating, the shapes of the input arrays should be the same, but the dimension along which we want to concatenate can be different. We can define the dimension along which we want to concatenate using the axis parameter. The default value of the axis parameter is 0.
<br>

- ### To use this function, we pass the input arrays as a tuple and then use the concatenate() function to concatenate them. The shape of the output array depends on the shapes of the input arrays.
<br>

- ### Before using the concatenate() function, it is important to note that the shapes of the input arrays should be the same except for the dimension along which we want to concatenate.
<br>

- ### The main difference between the concatenate() function and the append() function is that the append() function concatenates one array to another, while the concatenate() function concatenates multiple arrays. The append() function does not allow us to specify the dimension along which we want to concatenate, while the concatenate() function allows us to do so using the axis parameter.

In [121]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [122]:
a

array([[1, 2],
       [3, 4]])

In [123]:
b

array([[5, 6],
       [7, 8]])

In [124]:
np.concatenate((a, b)) # axis 0 default means column wise

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [125]:
# use axis 0
np.concatenate((a, b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [126]:
# use axis 1
np.concatenate((a, b),axis=1) 

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])