# Transpose Functions

- ## *np.moveaxis()*
- ## *np.rollaxis()*
- ## *ndrray.T*
- ## *np.transpose()*
- ## *np.swapaxes()*


# Rearranging Functions

- ## *np.flip()*
- ## *np.flipr()*
- ## *np.flipud()*
- ## *np.roll()*
- ## *np.rot90()*

# *np.moveaxis()*
<br>

- ### The NumPy moveaxis() function is used to change the dimensions of an array. The syntax of this function is numpy.moveaxis(a, source, destination), where 'a' is the input array, 'source' and 'destination' define the positions of the axes to be moved.
<br>

- ### As the name suggests, the moveaxis() function is used to move the dimensions of an array. In this function, we can specify which dimensions to move and to which position. When we use the moveaxis() function, we take some dimensions from the input array 'a' and place them in a different position.
<br>

- ### We need to specify the source argument in this function to indicate which dimensions to move, and the destination argument to indicate where to move them. These positions are 0-based index positions.
<br>

- ### The moveaxis() function is very helpful when we need to modify the dimensions of an array for a specific operation. Along with this, this function is also useful for understanding and manipulating the dimensions of an array.
<br>

# Parameters
<br>

- ## a Required
- ## source Required
- ## destination Required

In [1]:
import numpy as np

In [2]:
arr = np.array([
    [1,2],
    [3,4]
])

arr


array([[1, 2],
       [3, 4]])

<img src="../../images/2d_ax.png" style="display: block;margin-left: auto;margin-right: auto;
  width:30%; border-radius:0px 10px 10px 10px; height:30%;">

In [3]:
"""

[1]
    -----------  > [1,3]
[3]

[2]
    --------------> [2,4]
[4]

 replace 0 axis to 1
"""

np.moveaxis(arr,source=0,destination=1)



array([[1, 3],
       [2, 4]])

In [4]:
# 3d Array

data= np.array([
    [
        [1,2],
        [3,4],
    ],
    [
        [5,6],
        [7,8],
    ]
])

data

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

<img src="../../images/3d.png" style="display: block;margin-left: auto;margin-right: auto;
  width:50%; border-radius:0px 10px 10px 10px; height:50%;">

In [5]:
# so here 3 axis 0,1,2
# NOW MOVE THE AXIS 0 REPLACE TO 2

# axis 0  values
- ##  [1,5] [2,6]
- ##  [3,7] [4,8]

# axis 1  values
- ##  [1,2] [3,4]
- ##  [5,6] [7,8]

In [6]:
# before replaceing 
data

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [7]:
# now replace 0 with 1
np.moveaxis(data,source=0,destination=1) # now axis 0 replace with axis 1

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

## read this topic first if you can't understand the axis
## <a href="https://github.com/Mubeen-Ahmad/python_11/blob/main/Python/17_Numpy/Understand_Axis.ipynb">click here</a>

# *np.rollaxis()*
<br>

- ### The NumPy rollaxis(a, source, destination) function is used to change the dimensions of an array. The syntax of this function is numpy.rollaxis(a, source, axis=0), where a is the input array, source defines the position of the axis to be rolled, and axis defines the positions to which the axis is to be rolled.
<br>

- ### As the name suggests, the rollaxis() function is used to roll the dimensions of an array. This function takes some dimensions from the input array a and puts them in a different position. We can specify which axis to move to which position using this function.
<br>

- ### We use the source argument to specify which axis to take, and the axis argument to specify the positions to which the axis is to be moved. These positions are 0-based index positions.
<br>

- ### The rollaxis() function is very helpful when we need to modify the dimensions of an array for a specific operation. Additionally, this function is useful for understanding and manipulating the dimensions of an array.
<br>

# Parameters
<br>

- ## a Required
- ## axis Required
- ## start Optional

In [8]:
arr = np.array([
    [1,2],
    [3,4]
])
arr


array([[1, 2],
       [3, 4]])

In [9]:
# axis 0 
# [1, 2],
# [3, 4]

# axis 1
# [1, 3], 
# [2, 4]

# DEFALUT AXIS IS 0
arr

array([[1, 2],
       [3, 4]])

In [10]:
# change axis 0 to 1
np.rollaxis(arr,axis=1)

array([[1, 3],
       [2, 4]])

In [11]:
np.rollaxis(arr,axis=1,start=1) # start optional parameter for start moving 1 means skip 1

array([[1, 2],
       [3, 4]])

- ### NumPy mein swapaxes() function ka use, kisi array ke dimensions ko interchange karne ke liye kia jata hai. Is function ka syntax numpy.swapaxes(a, axis1, axis2) hai, jahan a input array hai aur axis1 aur axis2, swap kiye jane wale axis ki positions ko define karte hain.
<br>

- ### Swapaxes() function, input array a ke kisi bhi do dimensions ko interchange karne ke liye use kiya jata hai. Is function mein hum specify kar sakte hain ke konse axis ko kis position mein swap karna hai.
<br>

- ### Is function mein axis1 argument humein specify karna hota hai ke kaunse axis ko swap karna hai, aur axis2 argument mein humein specify karna hota hai ke usko kis axis ke sath swap karna hai. Ye positions, 0-based index positions hoti hain.
<br>

- ### Swapaxes() function ka use bahut hi helpful hai jab humein kisi specific operation ke liye array ke dimensions ko interchange karna ho.
<br>

- ### The main difference between moveaxis() and swapaxes() functions is that moveaxis() allows us to move the specified dimensions to any position while maintaining their order, whereas swapaxes() only swaps the specified dimensions without changing their order.
<br>

- ### For example, if we have a 3D array with dimensions (0, 1, 2), moveaxis() allows us to move any dimension to any position such as (1, 0, 2) or (2, 1, 0), while swapaxes() only allows us to swap two dimensions such as (1, 0, 2) or (0, 2, 1).

In [12]:
arr

array([[1, 2],
       [3, 4]])

In [13]:
new = np.swapaxes(arr,axis1=0,axis2=1)
new

array([[1, 3],
       [2, 4]])

In [14]:
np.swapaxes(new,axis1=1,axis2=0)

array([[1, 2],
       [3, 4]])

In [15]:
arr = np.array([[1,2,3,4,5,6]])
arr

array([[1, 2, 3, 4, 5, 6]])

In [16]:
np.swapaxes(arr,axis1=1,axis2=0)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# *ndrray.T  Method*
<br>

- ### In NumPy, the ndarray.T method is used to transpose a matrix. The syntax of this function is array.T, where the array is the input array.
<br>

- ### Matrix transpose means to interchange the rows and columns of a matrix. Transposing a matrix changes its shape, converting rows into columns and columns into rows.
<br>

- ### By using the ndarray.T Method, we can transpose a matrix, where we only need to provide the name of the input array. This function interchanges the order of rows and columns of the input array.
<br>

- ### This Method is very helpful when we need to transpose a matrix for matrix algebraic operations. In addition, we can also use this method to analyze the correlation between the rows and columns of the input array.

In [17]:
arr

array([[1, 2, 3, 4, 5, 6]])

In [18]:
arr.T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# np.transpose()
<br>

- ### In NumPy, the transpose() function is used to perform matrix transpose. The syntax of this function is numpy.transpose(arr, axes=None), where arr is the input array and axes argument is used to specify the order for transpose.
<br>

- ### Matrix transpose means to interchange the rows and columns of a matrix. Transposing a matrix changes its shape, and rows and columns are converted into each other.
<br>

- ### By using the transpose() function in NumPy, we can transpose a matrix by providing the input array. This function interchanges the order of rows and columns of the input arra
<br>

## Note in this function axis must be like a typle

In [19]:
arr

array([[1, 2, 3, 4, 5, 6]])

In [20]:
np.transpose(arr)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [21]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [22]:
arr.shape

(2, 2, 2)

In [23]:
np.transpose(arr)

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

In [24]:
np.transpose(arr,axes=(0,1,2)) # orignal form  0 , 1 ,2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [25]:
np.transpose(arr,axes=(1,0,2)) # orignal form  1 , 0 ,2

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [26]:
np.transpose(arr,axes=(2,0,1)) # orignal form  2 , 0 ,1

array([[[1, 3],
        [5, 7]],

       [[2, 4],
        [6, 8]]])

# *np.swapaxes()*
<br>

- ### The numpy.swapaxes() function is used to interchange two axes of a numpy array. This function returns a new view of the input array, with the specified axes swapped.

In [57]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
print(arr.shape)  # (2, 3)

(2, 3)


In [59]:
arr_swapped = np.swapaxes(arr, 0, 1)
print(arr_swapped.shape)  # (3, 2)

(3, 2)


In [60]:
arr_swapped

array([[1, 4],
       [2, 5],
       [3, 6]])

# *np.flip()*
<br>
    
- ### In NumPy, the flip() function is used to reverse the elements of an array. The syntax of this function is numpy.flip(m, axis=None), where m is the input array and the optional axis argument specifies which dimension of the array to reverse.
<br>

- ### By using the flip() function, we can reverse the elements of an array. For example, we can reverse the position of elements in a 1D array, or reverse the rows and columns of a 2D array.
<br>

- ### If the axis is not specified, the default axis -1 (last axis) is considered.
<br>

- ### By using the flip() function, we can modify the array by reversing its elements.

In [27]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
np.flip(arr)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [29]:
np.flip(arr,axis=0) # axis 0

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [30]:
np.flip(arr,axis=1) # axis 1

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [31]:
np.flip(arr,axis=-2) # axis -2

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

# *np.flipr()*
<br>

- ### In NumPy, the fliplr() function is used to reverse the columns of a 2D array. The syntax of this function is numpy.fliplr(m), where m is the input 2D array.
<br>

- ### By using the fliplr() function, we can reverse the columns of a 2D array. This means that we can turn the leftmost column of the array into the rightmost column, and the rightmost column into the leftmost column while keeping the order of the rows the same.
<br>

- ### By using this function, we can modify a 2D array, which can be helpful when we need to reverse the columns of an array.

In [32]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
np.fliplr(arr)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

# *np.flipud()*
<br>

- ### In NumPy, the flipud() function is used to reverse the rows of a 2D array. The syntax of this function is numpy.flipud(m), where m is the input 2D array.
<br>

- ### By using the flipud() function, we can reverse the rows of a 2D array. This means that we can make the topmost row of the array the bottommost row, and the bottommost row the topmost row. The order of the columns remains the same.
<br>

- ### Using this function, we can modify a 2D array and reverse its rows. This can be very helpful when we need to reverse the rows of an array for any purpose.

In [34]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
np.flipud(arr)

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

# *np.roll()*
<br>

- ### In NumPy, the roll() function is used to shift the elements of an array. The syntax of this function is numpy.roll(a, shift, axis=None), where "a" is the input array, "shift" specifies the number of positions to shift the elements, and "axis" is an optional argument that specifies the dimension along which the shift should happen.
<br>

- ### Using the roll() function, we can shift the elements of an array, such as shifting the positions of elements in a 1D array or shifting the rows and columns of a 2D array.
<br>

- ### If the "axis" argument is not specified, then the default value is -1, which means that the shift will happen along the last axis.
<br>

- ### By using the roll() function, we can modify the array by shifting its elements. This function can be quite useful when we need to shift the elements of an array.
<br>

# Parameters
<br>

- ## a Required
- ## shift Required
- ## axis Optional

In [36]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [37]:
np.roll(a=arr,shift=1)

array([3, 1, 2])

In [38]:
np.roll(a=arr,shift=2)

array([2, 3, 1])

In [39]:
np.roll(a=arr,shift=3)

array([1, 2, 3])

In [40]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
np.roll(a=arr,shift=1)

array([[9, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
np.roll(a=arr,shift=2)

array([[8, 9, 1],
       [2, 3, 4],
       [5, 6, 7]])

In [43]:
np.roll(a=arr,shift=3)

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [44]:
# also change axis
np.roll(a=arr,shift=2,axis=1)

array([[2, 3, 1],
       [5, 6, 4],
       [8, 9, 7]])

In [45]:
np.roll(a=arr,shift=2,axis=0)

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

# *np.rot90()*
<br>

- ### In NumPy, the rot90() function is used to rotate the elements of a 2D array by 90 degrees. The syntax of this function is numpy.rot90(m, k=1, axes=(0,1)), where m is the input 2D array, k specifies the degree of rotation (default value is 1, which means 90 degrees), and axes is a tuple that represents the rows and columns.
<br>

- ### By using the rot90() function, we can rotate the elements of a 2D array in a clockwise or anticlockwise direction by 90 degrees.
<br>

- ### Using this function, we can modify the 2D array, which is quite helpful when we need to rotate the elements of an array
<br>

# Parameters
<br>

- ## m Required
- ## k Optional
- ## axis Optional


In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
np.rot90(m=arr)

array([[3, 6, 9],
       [2, 5, 8],
       [1, 4, 7]])

In [48]:
np.rot90(m=arr,k=1) # here k 1 means 90 degree

array([[3, 6, 9],
       [2, 5, 8],
       [1, 4, 7]])

In [49]:
np.rot90(m=arr,k=1) # here k 2 means 90+90 = 180 degree

array([[3, 6, 9],
       [2, 5, 8],
       [1, 4, 7]])

In [50]:
np.rot90(m=arr,k=2) # here k 3 means 90+90+90 = 270 degree

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [51]:
arr.shape

(3, 3)

In [52]:
np.rot90(m=arr,k=2,axes=(0,1)) # change axis # according to shape

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])