# Useful Operations Functions

- ## *np.sum()*
- ## *np.product()*
- ## *np.prod()*
- ## *np.maximum()*
- ## *np.minimum()*
- ## *np.copysign()*

# Trigonometry Functions

- ## *np.sin()*
- ## *np.sinh()*
- ## *np.arcsin()*
- ## *np.arcsinh()*
- ## *np.cos()*
- ## *np.cosh()*
- ## *np.arccos()*
- ## *np.arccosh()*
- ## *np.tan()*
- ## *np.tanh()*
- ## *np.arctan()*
- ## *np.arctanh()*

In [1]:
import numpy as np

# *np.sum()*
<br>

- ### np.sum() is a function in the NumPy library of Python that is used to compute the sum of elements along a given axis of an array. It takes an array as an argument and returns the sum of all the elements in the array.
<br>

# Parameters
<br>

- ## a
- ## axis
- ## dtype
- ## out
- ## keepdims
- ## initial
- ## where

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# a parameter
np.sum(a=arr)

45

In [9]:
# axis parameter
np.sum(a=arr,axis=0)
# 1+4+7 = 12 
# 2+5+8 = 15
# 3+6+9 = 18

array([12, 15, 18])

In [10]:
# dtype parameter
np.sum(a=arr,dtype=np.float32)

45.0

In [17]:
# out parameter
temp = np.empty(3)
temp

array([4.6856002e-310, 0.0000000e+000, 7.9050503e-322])

In [18]:
np.sum(a=arr,axis=0,out=temp)

array([12., 15., 18.])

In [19]:
temp # out parameter save data in temp variable

array([12., 15., 18.])

In [24]:
# keepdims parameter
print("ARRAY Dim",arr.ndim)
np.sum(a=arr,keepdims=True)  

ARRAY Dim 2


array([[45]])

In [25]:
# use initial parameter

arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [31]:
np.sum(a=arr)

6

In [30]:
# now change starting value 
np.sum(a=arr,initial=2) # 2 -> + 1 + 2 + 3 = 8 

8

In [34]:
# where parameter
arr = np.arange(1,7)
arr

array([1, 2, 3, 4, 5, 6])

In [50]:
# now sum only odd numbers
condition = np.where(arr,arr%2 != 0,False)
condition

array([ True, False,  True, False,  True, False])

In [51]:
np.sum(a=arr,where=condition)

9

# *np.product()*
<br>

- ### "np.product() is a Python function that is available in the NumPy library. This function is used to calculate the product (multiplication) of all the elements inside a NumPy array.

In [53]:
arr = np.array([1,2,3]) # 1 * 2 * 3 = 6
arr

array([1, 2, 3])

In [54]:
np.product(arr)

6

# *np.prod()*
<br>

- ### np.prod() is a Python function that is available in the NumPy library. This function is used to calculate the product (multiplication) of all the elements inside a NumPy array. It is commonly used in data analysis, scientific computing, and numerical operations.
<br>

# Parameter
<br>

- ## a
- ## axis
- ## dtype
- ## out
- ## keepdims
- ## initial
- ## where

In [58]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
np.prod(a=arr)

362880

In [60]:
# axis
np.prod(a=arr,axis=0)

array([ 28,  80, 162])

### all parameters same as np.sum() 

# *np.max()*
<br>

- ### The np.max() function in NumPy is used to find the maximum value in an array. It takes an array as input and returns a scalar value, which is the maximum value in the array.

<br>

# Parameter
<br>

- ## a
- ## axis
- ## out
- ## keepdims
- ## initial
- ## where

In [63]:
np.max(a=arr)

9

In [62]:
# axis parameter
np.max(arr,axis=0)

array([7, 8, 9])

# *np.min()*
<br>

- ### The np.min() function in NumPy is used to find the maximum value in an array. It takes an array as input and returns a scalar value, which is the minimum value in the array.

<br>

# Parameter
<br>

- ## a
- ## axis
- ## out
- ## keepdims
- ## initial
- ## where

In [64]:
np.min(a=arr)

1

In [65]:
# axis parameter
np.min(arr,axis=0)

array([1, 2, 3])

In [67]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# *np.maximum()*
<br>

- ### np.maximum() is a NumPy function that returns the element-wise maximum of two arrays. It takes two arrays as input and returns an array containing the maximum value of corresponding elements in the input arrays.
<br>

# Parameters
<br>

- ## x1,x2
- ## where
- ## out

In [75]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 5])

In [76]:
np.maximum(a,b)

array([1, 2, 3, 5])

# *np.minimum()*
<br>

- ### np.minimum() is a NumPy function that returns the element-wise minimum of two arrays. It takes two arrays as input and returns an array containing the minimum value of corresponding elements in the input arrays.
<br>

# Parameters
<br>

- ## x1,x2
- ## where
- ## out

In [82]:
np.minimum(a,b)

array([1, 2, 3, 4])

# *np.copysign()*
<br>

- ### The np.copysign function is available in the NumPy library. Its meaning is also "always the same sign". This function is used to match the magnitude and sign.
<br>
    
- ### The np.copysign function takes two parameters, where the first parameter is the magnitude (i.e., quantity) and the second parameter is the sign (i.e., whether the quantity is positive or negative). The purpose of this function is to make the value of the magnitude positive or negative according to the sign.
<br>

- ### This function is used to maintain the sign in any mathematical calculation in the correct way

In [138]:
x = -2
x

-2

In [152]:
sqr = np.sqrt(abs(x)) # so - sign skip
sqr

1.4142135623730951

In [155]:
np.copysign(sqr, x) # use copysign

-1.4142135623730951

In [156]:
np.copysign(-10,10)

10.0

In [158]:
np.copysign(10,-10)

-10.0

# Trigonmetric Function

# *np.sin()*

In [88]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# *np.sinh()*

In [90]:
np.sinh(a)

array([ 1.17520119,  3.62686041, 10.01787493, 27.2899172 ])

# *np.arcsin()*

In [94]:
arr = np.array([0, 0.5, 0.7071, 0.866, 1])
arr

array([0.    , 0.5   , 0.7071, 0.866 , 1.    ])

In [96]:
np.arcsin(arr)

array([0.        , 0.52359878, 0.78538857, 1.04714675, 1.57079633])

# *np.arcsinh()*

In [97]:
np.arcsinh(arr)

array([0.        , 0.48121183, 0.65847341, 0.78338041, 0.88137359])

# *np.cos()*

In [98]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# *np.cosh()*

In [99]:
np.cosh(a)

array([ 1.54308063,  3.76219569, 10.067662  , 27.30823284])

# *np.arccos()*

In [101]:
np.arccos(arr)

array([1.57079633, 1.04719755, 0.78540775, 0.52364958, 0.        ])

# *np.arccosh()*

In [103]:
np.arccosh(a)

array([0.        , 1.3169579 , 1.76274717, 2.06343707])

# *np.tan()*

In [104]:
np.tan(arr)

array([0.        , 0.54630249, 0.8544987 , 1.17575023, 1.55740772])

# *np.tanh()*

In [105]:
np.tanh(arr)

array([0.        , 0.46211716, 0.6088551 , 0.69933613, 0.76159416])

# *np.arctan()*

In [106]:
np.arctan(arr)

array([0.        , 0.46364761, 0.61547519, 0.71370986, 0.78539816])

# *np.arctanh()*

In [115]:
np.arctanh(arr)

/tmp/ipykernel_79891/2021640537.py:1: RuntimeWarning: divide by zero encountered in arctanh
  np.arctanh(arr)


array([0.        , 0.54930614, 0.88136002, 1.31685629,        inf])