# AXIS
<br><br>

- ## Numpy Axis is a type of direction through which the iteration starts. 
<br>

- ## Every operation in numpy has a specific iteration process through which the operation proceeds.
<br>

- ## Moreover, there are two types of the iteration process
    - ## Column order and Fortran order. 
<br>

- ## Column order helps through the column axis
<br>

- ## Fortran order helps through the row axis.

<img src="../../images/axis_intro.jpg" style="display: block;margin-left: auto;margin-right: auto;
  width: 100%; border-radius:0px 10px 10px 10px; height:50%;">
<br>
<a href="https://www.programsbuzz.com/sites/default/files/inline-images/3D-Banner.jpg">Refference image</a>

<h3><p>In general, the axis parameter is used in NumPy functions that perform mathematical operations along a specific axis of an array, <br><br>such as np.sum(), np.mean(), np.max(), np.min(), np.std(), np.var(), np.argmax(), and np.argmin().</p></h3>

# 1-D 
<br>

## Axis 0: This refers to the first dimension of an array, which is often used to represent the rows of a matrix.

In [108]:
import numpy as np

In [109]:
arr = np.array([1,2])

In [110]:
arr

array([1, 2])

<img src="../../images/axis_1d.png" style="display: block;margin-left: auto;margin-right: auto;
  width:50%; border-radius:0px 10px 10px 10px; height:50%;">

In [112]:
arr.shape
# 2,0 here 0 is axis

(2,)

# sum operation

<img src="../../images/axis_2.png" style="display: block;margin-left: auto;margin-right: auto;
  width:50%; border-radius:0px 10px 10px 10px; height:50%;">

In [114]:
np.sum(arr,axis=0)

3

# Axis 1: 
<br>

## This refers to the second dimension of an array, which is often used to represent the columns of a matrix.

# 2-D

In [118]:
arr = np.array([
    [1,2],
    [3,4]
])

In [119]:
arr

array([[1, 2],
       [3, 4]])

<img src="../../images/2d_ax.png" style="display: block;margin-left: auto;margin-right: auto;
  width:50%; border-radius:0px 10px 10px 10px; height:50%;">

In [122]:
print(arr.shape)

(2, 2)


In [123]:
print(arr.ndim)

2


# Sum column Wise

In [128]:
np.sum(arr,axis=0)

array([4, 6])

<img src="../../images/2ax.png" style="display: block;margin-left: auto;margin-right: auto;
  width:50%; border-radius:0px 10px 10px 10px; height:50%;">

# sum Row Wise

In [130]:
np.sum(arr,axis=1)

array([3, 7])

<img src="../../images/ax2_.png" style="display: block;margin-left: auto;margin-right: auto;
  width:50%; border-radius:0px 10px 10px 10px; height:50%;">

# Axis 2: 
<br>

## This refers to the third dimension of an array, which is often used to represent different layers or slices of a three-dimensional array.

# 3-D 

In [136]:
data= np.array([
    [
        [1,2],
        [3,4],
    ],
    [
        [5,6],
        [7,8],
    ]
])


In [137]:
data

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

<img src="../../images/3d.png" style="display: block;margin-left: auto;margin-right: auto;
  width:50%; border-radius:0px 10px 10px 10px; height:50%;">

# axis 0 is the 3d values
- ##  [1,5] [2,6]
- ##  [3,7] [4,8]

In [139]:
np.sum(data,axis=0)

array([[ 6,  8],
       [10, 12]])

<img src="../../images/ax3_0.png" style="display: block;margin-left: auto;margin-right: auto;
  width:50%; border-radius:0px 10px 10px 10px; height:50%;">

# axis 1

In [141]:
np.sum(data,axis=1)

array([[ 4,  6],
       [12, 14]])

<img src="../../images/3dax_1.png" style="display: block;margin-left: auto;margin-right: auto;
  width:70%; border-radius:0px 10px 10px 10px; height:250px;">

# axis 2

In [142]:
np.sum(data,axis=2)

array([[ 3,  7],
       [11, 15]])

<img src="../../images/3dax_2.png" style="display: block;margin-left: auto;margin-right: auto;
  width:70%; border-radius:0px 10px 10px 10px; height:250%;">